### ISSUE TITLE
Incorrect HTML markup fix for nested lists

### ISSUE THREAD

**Issue by Florent2** [sparklemotion/nokogiri#1059]
When passing this incorrect markup to Nokogiri (incorrect because the sub `ul` can't be a direct child of the root `ul`), Nokogiri does not try to fix it, which is fine with me:

```
<ul>
  <li>item1</li>
  <ul>
    <li>subitem1</li>
  </ul>
  <li>item2</li>
</ul>
```

`Nokogiri::HTML("<ul><li>item1</li><ul><li>subitem1</li></ul><li>item2</li></ul").to_html` gives me back the same markup.

But if I pass the same kind of markup, just changing the root `ul` to `ol`

```
<ol>
  <li>item1</li>
  <ul>
    <li>subitem1</li>
  </ul>
  <li>item2</li>
</ol>
```

Nokogiri changes the markup and gives me back this incorrect markup:

```
<ol>
  <li>item1
</ol>
<ul>
    <li>subitem1</li>
</ul>
<li>item2</li>
```

`Nokogiri::HTML("<ol><li>item1</li><ul><li>subitem1</li></ul><li>item2</li></ol").to_html` 

Tested with Nokogiri 1.6.1

**Comment by JunichiIto** [comment]
I got the same problem in 1.6.7. I expect both of them should return the same markup.

**Comment by flavorjones** [comment]
Nokogiri depends on its underlying parse (libxml2 on MRI, and xerces/nekohtml on JRuby) for document correction.

Because of this, Nokogiri unfortunately has very little control over how documents are corrected.

If you feel strongly that this is a bug which needs to be addressed, I'd ask that you submit a bug report upstream.

I'm sorry that this isn't a very helpful reply.

**Comment by JunichiIto** [comment]
@flavorjones Okay, I understand.
FYI, similar issue already exists in libxml2 https://bugzilla.gnome.org/show_bug.cgi?id=759987
