### ISSUE TITLE
Closing tag for DIV inserted in a wrong place inside UL/LI

### ISSUE THREAD

**Issue by mislav** [sparklemotion/nokogiri#1135]
This HTML fragment:

``` html
<ul>
<li>A <div></li>       <!-- note the open DIV -->
<li>B</li>
</ul>
```

When parsed with Nokogiri and spit out using `to_html`, generates slightly different HTML:

``` html
<ul>
<li>A <div>
<li>B</li>

</div>      <!-- closing tag inserted in wrong place -->
</li>
</ul>
```

Notice that the `</div>` closing tag was inserted, but not in the correct position. The typical web browser would auto-close the DIV tag as soon as it encounters the first `</li>`. But Nokogiri fails to do that, and instead auto-closes the DIV when it encounters the `</ul>`.

The resulting HTML can break web page layouts as now the browser thinks that more than 1 DIV was closed here.

The behavior is the same in Nokogiri 1.5.11 and 1.6.3.

**Comment by flavorjones** [comment]
This behavior is definitely coming from libxml2's HTML parser which has complex logic around implicit closing tags and autocorrection.

FWIW, the HTML5 parser does the right thing and generates:

```html
<html><head></head><body><ul>
<li>A <div></div></li>
<li>B</li>
</ul>
</body></html>
```

I'd like to close this issue since there's nothing Nokogiri can easily do to change this behavior.

As is customary in these situations, I'm offering to assist in filing a bug report upstream; but the libxml2 maintainers have not been very responsive lately, especially since Steve Checkoway stepped down from maintaining, and so I'm not confident we'll get the result we want.

**Comment by stevecheckoway** [comment]
Just for the record, I haven't had any involvement with libxml2 other than as a user of the library.

**Comment by flavorjones** [comment]
Ahhhhh! Sorry, I didn't mean Steve Checkoway, I meant Nick Wellnhofer. Total brain fart, my apologies.
