### ISSUE TITLE
xpath //namespace::* returns garbage -> can lead to segfault

### ISSUE THREAD

**Issue by etm** [sparklemotion/nokogiri#1155]
warnings: []
    nokogiri: 1.6.3.1
    ruby:
      version: 2.0.0
      platform: x86_64-linux-gnu
      description: ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/var/lib/gems/2.0.0/gems/nokogiri-1.6.3.1/ports/x86_64-pc-linux-gnu/libxml2/2.8.0"
      libxslt_path: "/var/lib/gems/2.0.0/gems/nokogiri-1.6.3.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.28"
      compiled: 2.8.0
      loaded: 2.8.0

---------------------

Execute the following code for the file http://gruppe.wst.univie.ac.at/~mangler/SimTest.xml:

    require 'nokogiri'
    a = Nokogiri::XML::parse(File.open('SimTest.xml')){|config| config.noblanks.noent.nsclean.strict }
    b = a.xpath('//namespace::*').to_a
    puts b.length 

It tells that it finds 6464 namespaces. Most of them are binary garbage. i.e.

    #(Namespace:0x13bad48 {
       prefix = "pK\xC8\u0002",
       href = "\x90\xE6\x83\u0002"
       }),

Accessing them leads to segfaults. The first couple of namespaces are correct, but then (i suppose) it progresses into uncharted memory territory :-)

Funnily it works correctly for some XML files with namespaces. Funnily it works for some XML files with namespaces sometimes (heisenbug). The XML http://gruppe.wst.univie.ac.at/~mangler/SimTest.xml is the first one that i found that consistently lets me reproduce the error.

**Comment by flavorjones** [comment]
Looking at this today with @akshaysawant ... think we have a fix.

**Comment by flavorjones** [comment]
There's some history here, which I'll relate.

Originally @tenderlove committed dbda52b to try to plug a memory leak, but that was dereferencing possibly-invalid pointers during `deallocate` and was reverted.

Then, @ender672 committed 2675a75 which, though it didn't leak memory, introduced the bug you're seeing, which is that we're accessing the namespace nodes returned from an XPath query after the NodeSet has been GCed and freed the underlying namespace structs.

What I'd like to do is closer to what @tenderlove originally proposed, which is to wrap a `Nokogiri::XML::Namespace` ruby object around the `xmlNs` struct; except that we'll force the creation of the `Namespace` object and then let normal Ruby GC figure out when to free that node.

If we do this, then I think we'll have no invalid memory access and no leaks, and we'll be able to remove not only the `nokogiriNodeSetTuple` but all the namespace-related code in `xml_node_set.c`; the tradeoff is that we'll incur Object creation costs up front when we search for namespace nodes, but  that seems acceptable, because why would you search for a thing and then not use it?

Comments welcome, I'll probably drop this on a branch today and target it for 1.6.8.

**Comment by flavorjones** [comment]
Please see PR #1360 for my proposed fix, which is clean in valgrind and does not leak memory related to namespace xpath queries.

**Comment by flavorjones** [comment]
PR merged onto master, will be fixed in 1.6.8.
