### ISSUE TITLE
element name case changes when added to document with different encoding

### ISSUE THREAD

**Issue by dcorrigan** [sparklemotion/nokogiri#1158]
Hi,

It looks like element names are serialized in a case-insensitive way if the element is added as a string to a document that declares a different encoding:

``` ruby
# encoding: utf-8
f = <<-EOT
<?xml version="1.0" encoding="us-ascii"?>
<root>
  <p>foo</p>
</root>
EOT
r = Nokogiri.XML(f)
p = r.at_css('p').replace('<yYy>©bar</yYy>')
puts r.to_s
```

This produces:

```
<?xml version="1.0" encoding="us-ascii"?>
<root>
  <yyy>&#169;bar</yyy>
</root>
```

I tested this on nokogiri 1.6.3.1, libxml2 2.8.0. Is this a libxml2 problem, maybe?

**Comment by flavorjones** [comment]
Apologies for not replying for such an embarrassingly long time.

Fragment parsing is a bit complicated because libxml2 doesn't recover from errors while parsing a fragment _in the context of a specific node_ (e.g., `node.parse(...)` as opposed to `Nokogiri::XML::DocumentFragment.parse(...)`).

When an error (like the encoding error here, or any other syntax error) is encountered, Nokogiri's fallback behavior is to parse the fragment _outside_ the context of the node. Unfortunately, though, it was using a hardcoded class to do this: `Nokogiri::HTML4::DocumentFragment`. This uses the HTML parser and causes all elements to be downcased.

See #2388 for fix.
