### ISSUE TITLE
Segfault on OS X 10.10.2

### ISSUE THREAD

**Issue by cassianoleal** [sparklemotion/nokogiri#1237]
Nokogiri segfaults on my system. I have cross-tested nokogiri versions 1.6.6.2, 1.6.6.1, 1.6.5 and 1.6.4.1 with Ruby 1.9.3-p547, 2.0.0-p576 and 2.1.3.

The crash happens right after requiring nokogiri.

I have created https://gist.github.com/cassianoleal/bdf508d12f01a899ec6a with the stack trace and the crash report for nokogiri 1.6.4.1 under Ruby 2.0.0-p576.

**Comment by flavorjones** [comment]
Hi,

Generally if Ruby crashes like this, it's due to using a C extension that was compiled with different assumptions (different Ruby, different OS, different libraries, etc.). In this case, it appears that Nokogiri may have been compiled with different assumptions than it's currently running under.

Have you recently upgraded Ruby or your OS on your machine? It looks like you're running 10.10.2, so I'm guessing the answer is "yes".

Does this happen if you re-install Nokogiri? I can tell you that 10.10.2 also broke some things during install-time that we haven't been able to diagnose yet (see #1235), so you may not be able to answer this question.

ccing @zenspider so he's aware.

**Comment by zenspider** [comment]
I just confirmed that nokogiri installed fine with stock ruby on 10.10.2 (final) for me.

If there are still problems for you, we need to compare notes and see what variables are different.

**Comment by cassianoleal** [comment]
This is odd.

I don't use the stock Ruby at all. I install my rubies using chruby/ruby-install. After installing 10.10.2 and seeing the segfault, I deleted all my rubies and gems and started over, but still had the segfault. After doing `gem uninstall nokogiri` and `gem install nokogiri`, the segfault was gone.

I have no explanation for that apart from that I'm sure I screwed up at some point. :)

Closing this now, thanks for your help!

**Comment by zenspider** [comment]
> On Jan 28, 2015, at 00:59, cassiano <notifications@github.com> wrote:
> 
> I don't use the stock Ruby at all. I install my rubies using chruby/ruby-install. After installing 10.10.2 and seeing the segfault, I deleted all my rubies and gems and started over, but still had the segfault. After doing gem uninstall nokogiri and gem install nokogiri, the segfault was gone.
> 
> I have no explanation for that apart from that I'm sure I screwed up at some point. :)

I don't think you screwed up. Something, at some point, decided it was OK to only build an i386 version of... something else. It stuck around and disagreed with a new install of nokogiri upon linkage. you still had the segfault because you didn't have the new build of nokogiri and your old build had the same linkage problem the new one did. Cleaning it out and reinstalling nokogiri got everyone on 64 bit.

Knowing what that "something else" part is would be nice, but isn't necessary.

@flavorjones: we might want to update the instructions that if someone built their own ruby and gets this i386 linker error, that they'll want to rebuild their ruby at that time. It was probably linked to something on apple's side that changed architectures.

**Comment by cassianoleal** [comment]
Ok... I went ahead and deleted all rubies and gems once again, then reinstalled Ruby 2.1.3 and my bundle.

Guess what? Segfault again... Now I'm at a complete loss...

**Comment by cassianoleal** [comment]
Nevermind... Seems like the segfault this time was with the `json` gem, not `nokogiri`.

**Comment by zenspider** [comment]
@flavorjones: we also might want to update the instructions and blame the `json` gem.

**Comment by flavorjones** [comment]
Thanks for following up, everybody. If somebody else sees this, hopefully they'll find it on the Googles and comment, and then I'll document it.
