### ISSUE TITLE
Parser halt when there is a NUL char in the parsed string

### ISSUE THREAD

**Issue by juliennicolas** [sparklemotion/nokogiri#1240]
Reproducing : 
```
2.0.0-p247 :042 > a = "<p>\000<b>plop<b/><p>"
=> "<p>\x00<b>plop<b/><p>" 
2.0.0-p247 :043 > Nokogiri::HTML(a).search("//b")
=> []
```

And there is no parse errors :
```
2.0.0-p247 :047 > Nokogiri::HTML(a).errors
 => [] 
````

It halt when the NUL is hit :
```
2.0.0-p247 :045 > Nokogiri::HTML(a)       
 => #<Nokogiri::HTML::Document:0x3fe91a6badbc name="document" children=[#<Nokogiri::XML::DTD:0x3fe91a6be728 name="html">, #<Nokogiri::XML::Element:0x3fe91a6bfa74 name="html" children=[#<Nokogiri::XML::Element:0x3fe91a6bf7a4 name="body" children=[#<Nokogiri::XML::Element:0x3fe91a6bf588 name="p">]>]>]>
```

**Comment by flavorjones** [comment]
Hi @juliennicolas,

This happens on MRI because the underlying libxml2 parser is written in C. C string have the convention of using a null character to represent end-of-string.

Note that this doesn't happen in the JRuby implementation, as Java strings also have a "length" property.

Unfortunately, there's not much we can do for this. If you have a document that you think has null characters in it, you may want to "pre-process" them with something like:

```ruby
html_string.gsub!(/\0/,"")
```

**Comment by JonRowe** [comment]
That doesn't stop it appearing in the wild unfortunately (page is valid HTML otherwise)
