### ISSUE TITLE
Still more validity errors

### ISSUE THREAD

**Issue by rubys** [sparklemotion/nokogiri#1262]
test case:

    require 'nokogiri'
    doc = Nokogiri::HTML::Document.new()
    x1 = Nokogiri::XML::Element.new('a', doc)
    x1.set_attribute('id', 'x')
    x2 = Nokogiri::XML::Element.new('a', doc)
    x2.set_attribute('id', 'x')

related: https://github.com/sparklemotion/nokogiri/issues/1208 and https://github.com/sparklemotion/nokogiri/issues/1208

**Comment by flavorjones** [comment]
OK, will fix for 1.6.7.

**Comment by flavorjones** [comment]
Interesting: my first attempt at a fix handles the error and adds it to the document `@errors` array. However, the JRuby implementation doesn't raise an error in this case.

@rubys Would an acceptable solution here be to simply silence this error, rather than capture it in a platform-dependent way? I'm assuming that if someone's building a document using the API this way that they know what they're doing ...

I'll proceed by silencing unless you have objections and an alternative solution.

**Comment by rubys** [comment]
I'm OK with silencing.

**Comment by epinault** [comment]
is this released? I see the changelog but I don t see any updated gem. I have the same issue and need a way to silence them :(

**Comment by demetrios** [comment]
I'm being bombarded with `element section: validity error : ID <some-id> already defined` warnings. I see that this appears to have been fixed back in March but never released as an update.

Is something holding `v1.6.7` back or was this perhaps forgotten?
