### ISSUE TITLE
Attribute loses namespace when node moved

### ISSUE THREAD

**Issue by dcorrigan** [sparklemotion/nokogiri#1278]
I found the following from another user in the nokogiri-talk page. I'm encountering the same issue, so I'm posting it here. I was using Nokogiri 1.6.6.2 and MRI 2.1.4 on Ubuntu 14.

I'd guess the issue stems from the namespace definitions being different objects, but that seems like something that should be resolved without losing the namespace of the added node.

Thanks for any insight or info!

From the other user:
An attribute lost a namespace, when a node append an other document's element with the namespaced attribute.
I'm using Nokogiri 1.6.6.2 on CRuby 1.9.3.
This problem is similar to https://groups.google.com/forum/#!msg/nokogiri-talk/xJID0rVqikA/oDBvwhy4lgMJ

Running this:

```
require 'nokogiri'

raw_xml = <<"EOS"
<?xml version="1.0"?>
<Root xmlns:prefix="namespace">
  <Element prefix:attribute="value"/>
  <Add/>
</Root>
EOS

src = Nokogiri.XML(raw_xml){|c|c.noblanks}
doc = Nokogiri.XML(raw_xml){|c|c.noblanks}

child = src.xpath('//Element').first
#puts child.to_xml
doc.xpath('//Add').first.add_child(child)
#puts child.to_xml
#puts doc.to_xml

__END__
```
I would expect doc.to_xml to produce:
```
<?xml version="1.0"?>
<Root xmlns:prefix="namespace">
  <Element prefix:attribute="value"/>
  <Add>
    <Element prefix:attribute="value"/>
  </Add>
</Root>
```

However, calling doc.to_xml actually produces:

```
<?xml version="1.0"?>
<Root xmlns:prefix="namespace">
  <Element prefix:attribute="value"/>
  <Add>
    <Element attribute="value"/>
  </Add>
</Root>
```
source: https://groups.google.com/forum/#!topic/nokogiri-talk/PgxWEszbgD4

**Comment by flavorjones** [comment]
I responded to the email thread, but I'll reproduce my response here ...

I don't think anything is wrong; this mystified me for a few minutes as well. The justification for the current behavior is simply that we're not doing the comparison of namespace URIs when moving nodes between documents. I couldn't find any sort of XML specification stating how this should work; so we likely adopted this behavior because it was the easiest thing to do at the time. (And please note that it works this way consistently in both MRI and JRuby.)

Worth noting that this code works fine if you're simply reparenting nodes within a document; this example displays odd behavior because the node is moving *between* documents.

Can you tell me why you think one way is better than another? I'd love to beter understand your particular use case.

**Comment by dcorrigan** [comment]
Sorry for the late response; I missed the notification.

My use case involves moving content nodes between docx files (within the internal OOXML files). OOXML docs have at least a half dozen different namespaces within each document. Right now I resolve the namespaces of attributes after they've been imported to a new doc.

Without there being any XML spec for resolving this, I can understand the current behavior. I guess a new feature could allow for namespace URI comparison against imported nodes to be turned on as a configuration option on the target document. That way the current behavior remains the default. If you think that's outside the scope of the gem, though, feel free to close.

**Comment by kbrock** [comment]
I ran into something similar with #1200 I think the solution may be to add a duplicate of the node instead of the node itself. `add_child(node.dup)`

My case I moved from one document to another. But I hope that will help solve your problem too.

**Comment by dcorrigan** [comment]
@kbrock , thanks, that's useful and works. 

@flavorjones This doesn't seem like much of a bug anymore, so I'm closing it. Thanks for your help.
