### ISSUE TITLE
Building of native extensions fails

### ISSUE THREAD

**Issue by jasajona** [sparklemotion/nokogiri#1290]
Nokogiri 1.6.6.2 installs with no problem. 1.4.x version fails. Using ubuntu + rvm (all required libraries are installed).

```
pm@sniegas:~$ gem install nokogiri -v '1.4.3'
Fetching: nokogiri-1.4.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
    ERROR: Failed to build gem native extension.

    /home/pm/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150519-7580-2yzgsg.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/pm/.rvm/rubies/ruby-2.2.1/bin/$(RUBY_BASE_NAME)
extconf.rb:10:in `<main>': uninitialized constant Config (NameError)

extconf failed, exit code 1

Gem files will remain installed in /home/pm/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.4.3 for inspection.
Results logged to /home/pm/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/nokogiri-1.4.3/gem_make.out
```

**Comment by twe4ked** [comment]
`Config` was replaced by `RbConfig` in Ruby `2.2.0` (according to: https://github.com/chef/ohai/issues/453). I [manually fixed it](http://stackoverflow.com/a/30332317/826820).

**Comment by endangurura** [comment]
Having the same problem, 

gem install nokogiri
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby22 -r ./siteconf20150520-30341-1u91ypf.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)22
	--help
	--clean
	--use-system-libraries
/usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mini_portile (LoadError)
	from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from extconf.rb:395:in `<main>'

extconf failed, exit code 1

**Comment by flavorjones** [comment]
Sorry, we no longer support the 1.4.x branch, for what should be obvious reasons. For an idea of how old nokogiri 1.4.3 is, I invite you to visit this page:

https://rubygems.org/gems/nokogiri/versions
