### ISSUE TITLE
Can not handle '&' in attribute in JRuby

### ISSUE THREAD

**Issue by scarfacedeb** [sparklemotion/nokogiri#1295]
After migrating from mri to jruby, I noticed that Nokogiri doesn't parse all of the xml documents till the end.

Further investigation revealed that it stops at invalid elements with unescaped _&_ in their attributes.
MRI/C-version of Nokogiri worked fine.

Related: #525 

``` ruby
html = "<p class='they & us'>You & me </p>"
xml = Nokogiri::XML(html)
puts xml # == <?xml version="1.0"?> only
```

**Comment by twalpole** [comment]
What version of nokogiri are you using?  With the latest (1.6.6.2) your code just drops the illegal unescaped &s and prints out

&lt;?xml version="1.0"?>
&lt;p class="they  us">You  me &lt;/p>

It does raise the issue of why you're parsing html using the XML parser though, instead of with the html parser ( Nokogiri::HTML(html) ) which tries its best guess to figure out what you mean and will escape the &s for you, producing

&lt;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
&lt;html>&lt;body>&lt;p class="they &amp;amp; us">You &amp;amp; me &lt;/p>&lt;/body>&lt;/html>

**Comment by jvshahid** [comment]
verified on master

**Comment by flavorjones** [comment]
The behavior described here is due to the underlying parsers, libxml2 and xerces. The XML spec does not address how to recover from malformed documents and so each parser tends to choose something slightly different.

Unfortunately there's no easy way for Nokogiri to change this behavior. The Guiding Principles called out in Nokogiri's README state a goal of:

> be a thin-as-reasonable layer on top of the underlying parsers, and don't attempt to fix behavioral differences between the parsers

So I'm going to close this with apologies that we can't be more helpful.
