### ISSUE TITLE
Nokogiri should come with prebuilt binary dependencies

### ISSUE THREAD

**Issue by behrangsa** [sparklemotion/nokogiri#1324]
Nokogiri is one of those dependencies that is a pain in the neck to install on OS X. If you Google this, you will see thousands of results about installation problems.

Sometimes it is due to `libiconv`, `libxml`, or `libxslt`. Sometimes it fails due to other reasons.

In Nodejs, there's this tool called [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) that allows libraries that depend on native code get packaged with binaries for common operating systems and skip the compilation step during installation.

Also some libraries fallback to pure JS code, which is slower, but at least doesn't keep people from doing their work.

It would be nice if Nokogiri either could fallback on pure Ruby code or come with prebuilt binaries for common operating systems (if this is possible with Ruby gems).

Or if it was smarter and could inspect the system for such things as `brew`, `ports`, `xcode-select`, etc. and automatically prepare the system for successful installation.

**Comment by flavorjones** [comment]
@behrangsa, thanks for your comments. I'd invite you to start a conversation on the mailing list about this, rather than express your opinion in a github issue. That's where the community of users and developers might engage with you on this topic.

I'll also mention that we're trying very hard to have this page be the canonical place for help installation Nokogiri:

    http://www.nokogiri.org/tutorials/installing_nokogiri.html

If you haven't found that page, can you help us SEO it better by tweeting or blogging about it? If you found it and it wasn't useful, can you help us improve it? The tutorials on that site are all open-source and we take PRs and watch Issues.

**Comment by flavorjones** [comment]
Just a note that v1.11.0 will be coming out shortly with precompiled libraries. See https://github.com/sparklemotion/nokogiri/issues/2075 for details.
