### ISSUE TITLE
Nokogiri Truck Factor

### ISSUE THREAD

**Issue by gavelino** [sparklemotion/nokogiri#1328]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Nokogiri** and obtained a value of **2**.

The developers responsible for this TF are:

Aaron Patterson - author of 57% of the files
Yoko Harada - author of 27% of the files

To validate our results, we would like to ask **Nokogiri** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Nokogiri**?

(b) Do you agree that **Nokogiri** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Nokogiri** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by flavorjones** [comment]
a) no, both developers are currently inactive.

b) no, both developers are currently inactive and I'm about to cut a new release.

c) yes, shared ownership of files, otherwise known as "community"

Based on this, I'm going to assert that your algorithm is not appropriate for projects like Nokogiri where there's shared ownership of many files over a long period of time.

I'm happy to help you better describe our project -- maybe you'd like to ask more open-ended questions?
