### ISSUE TITLE
No children when it actually has 

### ISSUE THREAD

**Issue by marguerite** [sparklemotion/nokogiri#1329]
Hi,

I parsed a url like this,

<pre>
url = "https://build.opensuse.org/package/show/home:MargueriteSu:branches:devel:languages:nodejs/nodejs-accord"
html = Nokogiri::HTML(open(url))
doc = html.xpath('//div[@id="content"]/div[3]/div[2]')
p doc
</pre>

as you can see by visiting the url, there's still another div[@id="package_buildstatus"] under the xpath I used, but the returned object from above code doesn't have any child.

Is that a bug? or something wrong with my code?

**Comment by flavorjones** [comment]
Hi @marguerite,

Thanks for asking this question. Apologies for not responding earlier, I missed the notification.

Generally, the team uses GH Issues for bug reporting, and not for asking general usage questions, as noted at http://www.nokogiri.org/tutorials/getting_help.html

But since it's been so long since you asked, I'll try to help.

I'd like to turn this around, though -- can you explain what you're trying to accomplish? Which `div` are you trying to capture? I ask because, right now, there is nothing with an `id` of `package_buildstatus` on that page (2015-08-31 07:46:23 -0400).

Can you provide example code that doesn't depend on a live URL (instead, provide static HTML with the code)?

**Comment by marguerite** [comment]
@flavorjones 

Hi, thanks for looking at it.

![](http://paste.opensuse.org/view/raw/11003084)

I want the href value of this "a" element.

Marguerite

**Comment by flavorjones** [comment]
Hi @marguerite,

Your reply hasn't helped me understand the problem you're trying to solve.

If you provide example code that doesn't depend on a live URL (instead, provide static HTML with the code), I'll reopen.

Again, you should consider using the mailing list for more immediate responses.
