### ISSUE TITLE
Incorrect meta encoding for HTML documents

### ISSUE THREAD

**Issue by hahcho** [sparklemotion/nokogiri#1340]
[Link for the problematic page](http://www.altex.ro/electrocasnice-mari/incalzire-aer-conditionat/aparate-de-aer-conditionat/filtru/p/4). This page has its meta charset tag set incorrectly:

    <meta charset="text/html; charset=utf-8">

I have seen this in other pages. Maybe because it is generated automatically with the `Content-Type` meta tag.

Looking at [#meta_encoding](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/HTML/Document#meta_encoding-instance_method) I see that it will return just the content of the `charset` attribute(when I expect to return utf-8). The question is - is this the expected behavior?

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question. I don't fully understand what you're asking, though.

Can you please provide a snippet of code, along with markup, that demonstrates what you're seeing? Linking to outside web sites is generally not a great practice for reporting bugs, as that content will change over time.

**Comment by EricPMulligan** [comment]
The `charset` attribute in the `meta` element was introduced in HTML5 to replace the following:

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

This doesn't seem to be an issue with this gem, but an issue on the end of the problematic website who simply outputted the same value of the `content` attribute to the `charset` attribute which doesn't follow the new standard.

**Comment by knu** [comment]
It is expected behavior for meta_encoding to return a charset attribute value in string, as described in test/html/test_document.rb, and we have no plan to support parsing of <meta charset> containing a whole Content-Type.

**Comment by knu** [comment]
Actually HTML5 defines a recommended algorithm to extract a charset string from a meta element: https://html.spec.whatwg.org/multipage/infrastructure.html#extracting-character-encodings-from-meta-elements
Our simple implementation currently does not follow this, but the result is the same in this case.  The charset attribute value inside double quotes is not a valid encoding name, so there is no way it could return "utf-8".

**Comment by hahcho** [comment]
I was just asking if this is supposed to be the behavior. I mean a lot of the html documents do not follow the standards but are still out there. This is something I have come across a lot.

**Comment by flavorjones** [comment]
@hahcho Nokogiri does claim to "fix" some broken markup, but in most cases this simply means, "don't do something stupid when you encounter broken markup" and not "guess what the author intended".

Everyone is going to have a different opinion on how Nokogiri should interpret markup that's not following standards, because ... the markup isn't following standards.

If you'd like to suggest some particular implementation for how Nokogiri should interpret this particular failure, we'll gladly review a PR. However, I'm not entirely sure we'd accept it.

I hope you consider this to be a fair response to your question?

Also, in the future, please send questions to the mailing list, so that conversations can be had in a more visible place. We prefer to reserve GH Issues for bug reports and pull requests. We document our reasoning for this policy here:

    http://www.nokogiri.org/tutorials/getting_help.html

Cheers, and thank you for using Nokogiri!

-mike

**Comment by hahcho** [comment]
@flavorjones thanks for the answear. 

I will not make PR, I was just interested in the policy about this kind of behavior. 

Sorry for the PR, wil read the contribution rules next time.
