### ISSUE TITLE
Installing nokogiri on docker SOMETIMES fails for various gems

### ISSUE THREAD

**Issue by krainboltgreene** [sparklemotion/nokogiri#1347]
When installing on a docker container any gem that depends on nokogiri seems to have a chance to fail to install nokogiri despite libxml2 being installed:

```
root@8d13f6c18f81:/usr/src/application# apt-get install libxml2-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxml2-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

This is a log of me installing: https://gist.github.com/krainboltgreene/a9263dcf3d2f18165405

The contents of `/usr/src/application/gems/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/nokogiri-1.6.6.2/gem_make.out`: https://gist.github.com/krainboltgreene/7c8cbcc794f10616147b

The contents of `/usr/src/application/gems/ruby/2.1.0/gems/nokogiri-1.6.6.2/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.2/compile.log`: https://gist.github.com/krainboltgreene/9b02bac88fb461e34774

**Comment by flavorjones** [comment]
Hi @krainboltgreene,

Thanks for asking this question. Nokogiri 1.6.6.2 vendors a version of libxml2 and libxslt, so you shouldn't need to apt-get install them (and, in fact, without using `--use-system-libraries` nokogiri's installation process will ignore them).

In your `compile.log` I spot this line:

> virtual memory exhausted: Cannot allocate memory

My guess is that you need to bump up the amount of memory allocated to your Docker container so that the linker can run.

If you have followup questions, please ask them on the mailing list, as requested at http://www.nokogiri.org/tutorials/getting_help.html so that other people will be able to easily find our conversation in the future.

Thanks!

**Comment by krainboltgreene** [comment]
Awww yesh. You rock!

**Comment by flavorjones** [comment]
BOOM. Virtual high-five.
