### ISSUE TITLE
Nokogiri unescapes already escaped single/double quotes

### ISSUE THREAD

**Issue by livathinos** [sparklemotion/nokogiri#1363]
When using Nokogiri to parse a piece of HTML, single and double quotes that are already escaped are being reverted back to their non escaped form. For example:

```ruby
Nokogiri::HTML.fragment("<p>&#39; &#x27;</p>").to_html
=> "<p>' '</p>"

Nokogiri::HTML.fragment("<p>&#34; &#x22; &quot;</p>").to_html
=> "<p>\" \" \"</p>"
```

The same does not happen for other characters, like `&gt;` or `&amp;`:

```ruby
Nokogiri::HTML.fragment("<p>&gt; &amp;</p>").to_html
=> "<p>&gt; &amp;</p>"
```

This creates issues when feeding Nokogiri some already (maybe partially) escaped content.

**Comment by bquorning** [comment]
I’m also confused about the internal unescaping of other HTML entities. For example:
```
>> fragment = Nokogiri::HTML.fragment("&lt;script&gt;")
=> #<Nokogiri::HTML::DocumentFragment:0x3ffe28d1f810 name="#document-fragment" children=[#<Nokogiri::XML::Text:0x3ffe28d1edd4 "<script>">]>
>> fragment.text
=> "<script>"
>> fragment.to_html
=> "&lt;script&gt;"
```

**Comment by flavorjones** [comment]
Thanks for asking these questions!

@bquorning - The `#text` method emits a string suitable for a textual context, e.g. an email. In this case, the entities are unescaped because plaintext. The `#to_html` method is intended to emit a string suitable for rendering within an HTML document, so it will be rendered properly by a browser. Make sense?

@livathinos - This behavior is, unfortunately, part of libxml2's code and is very intentional. Some context is here:

> https://bugzilla.gnome.org/show_bug.cgi?id=127877

and the related commit is here:

> https://git.gnome.org/browse/libxml2/commit/?id=d453255

It's notable that quotes aren't escape when they're part of attributes (e.g., where the quote may be part of an attribute string); and that Neko+Xerces (the Java libraries used by Nokogiri in JRuby) behave the same way.

Hope this helps you both!

**Comment by bquorning** [comment]
@flavorjones Thanks for you reply. I understand your explanation of the `#text` and `to_html` methods, and realize now that my question probably wasn’t formulated all that well :-)

If I understand that libxml2 commit correctly, then `"` is no longer escaped on output. But the question is, why are `&#39;`, `&#x27;`, `&#34;`, `&#x22;`, `&lt;` and `&gt;` even unescaped *on input*?

As seen in the first two lines of my example above, these characters are unescaped in Nokogiri’s child node:

```
>> fragment = Nokogiri::HTML.fragment("&lt;script&gt;")
=> #<Nokogiri::HTML::DocumentFragment:0x3ffe28d1f810 name="#document-fragment" children=[#<Nokogiri::XML::Text:0x3ffe28d1edd4 "<script>">]>
```

I’m sorry if it sounds like I’m asking you to defend code that was committed to libxml2 12 years ago. I’m not. I’m just curious, and assume that you know more about libxml2 than I do.

**Comment by flavorjones** [comment]
@bquorning Thanks for asking.

You're using the output from `Node#inspect` to make conclusions about what's escaped and what's not escaped. This is probably not a good idea, as the `#inspect` method, for text nodes, is simply this:

> https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml/pp/character_data.rb#L12-L14

that is, it simply calls `#text`, which behaves as described above.

To restate this another way, `#inspect` outputs a version of the string contents that would be suitable for a __textual__ context, and so it appears unescaped.

If I'm not answering your questions, could you try to rephrase the question in terms of behavior? Ideally sample code showing expected behavior and actual behavior.
