### ISSUE TITLE
on master, some encoding tests fail on Windows

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1387]
see comment on commit https://github.com/sparklemotion/nokogiri/commit/895c84936faa33ae29ac80af6aec49f08f2034b5 for background

**Comment by flavorjones** [comment]
tagging @larskanis in case he's got context to solve this.

**Comment by larskanis** [comment]
Thanks Mike for the notification! I already opened https://github.com/sparklemotion/nokogiri/pull/1385 to address this. Would be nice if you could review it. The issue in this tests was that `File.read("my.xml")` returns a string with `cp843` encoding on Windows. This disables the `EncodingReader`, so that I changed it to `File.open` .
