### ISSUE TITLE
A bit confusing xpath behaviour

### ISSUE THREAD

**Issue by keysen** [sparklemotion/nokogiri#1414]
Hello,

Just a question, I was not able to find an answer by looking in the doc. 

I have a case where #xpath is returning a boolean instead of an array, it's a bit confusing, is this normal ? 
I mean when I do: 
```ruby
Nokogiri::HTML.fragment('<p>Hello dear</p><p class="orange">Yataaa</p>').xpath(".orange")  => true
Nokogiri::HTML.fragment('<p>Hello dear</p><p class="orange">Yataaa</p>').xpath("..orange")  => false
Nokogiri::HTML.fragment('<p>Hello dear</p><p class="orange">Yataaa</p>').xpath("orange") =>  []
```
I often do xpath(selector).each because I though xpath was always returning an array, but I found some examples where it's returning a boolean. Can someone tell me whether or nor it's a wanted behaviour ?

Thanks

**Comment by flavorjones** [comment]
It took me a bit to figure this out. The explanation is hysterical, at least in the relatively mundane world of HTML parsing. Bear with me.

First, let me point out that you're passing CSS queries into the `#xpath` method. You probably want to use the `#css` method instead, if you're looking for the element with the class "orange". Like this:

```
html = '<p>Hello dear</p><p class="orange">Yataaa</p>'
puts Nokogiri::HTML.fragment(html).css(".orange")
# => <p class="orange">Yataaa</p>
```

OK, but let's dig into why Nokogiri is behaving this way. The important bit is that libxml2 has an XPath query parser, which appears to tokenize this in a very curious, whitespace-ignorant way.

Let's first observe that this query explodes, telling us that ".foo" is invalid XPath syntax:

```
> puts Nokogiri::HTML.fragment(html).xpath(".foo").inspect
home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/searchable.rb:165:in `evaluate': Invalid expression: .foo (Nokogiri::XML::XPath::SyntaxError)
```

This is interesting because ".foo" is invalid, but ".orange" is somehow OK. This was my first WTF moment, but working backwards reveals:

```
puts Nokogiri::HTML.fragment(html).xpath(".orange") # => true
puts Nokogiri::HTML.fragment(html).xpath(".orang") # => true
puts Nokogiri::HTML.fragment(html).xpath(".oran") # => true
puts Nokogiri::HTML.fragment(html).xpath(".ora") # => true
puts Nokogiri::HTML.fragment(html).xpath(".or") # Invalid expression: .or (Nokogiri::XML::XPath::SyntaxError)
```

And here the light bulb went off for me. I'll refer you to the section of the XPath spec on Booleans:

> https://www.w3.org/TR/xpath/#booleans

and you'll see that "or" is a keyword that returns a boolean if either the left or right hand side are "truthy". So the query ".orange" is being parsed and interpreted as ". or ange". In XPath, "." refers to the context node, which always exists, and so this is truthy. "ange" refers to a node named `ange`, which doesn't exist in this doc and is hence "falsey".

```
puts Nokogiri::HTML.fragment(html).xpath(".orange") # => true
puts Nokogiri::HTML.fragment(html).xpath(". or ange") # => true
```

The query "..orange" is interpreted as ".. or ange". In Xpath, ".." refers to the context node's parent, which doesn't exist for a fragment or a document root, and so that's "falsey". Note that if we pair ".." with something that *does* exist, we can make this entire thing return true:

```
puts Nokogiri::HTML.fragment(html).xpath("..orange") # => false
puts Nokogiri::HTML.fragment(html).xpath(".. or ange") # => false
puts Nokogiri::HTML.fragment(html).xpath(".. or p") # => true
puts Nokogiri::HTML.fragment(html).xpath("..orp") # => true
```
 Finally, searching for "orange" is actually doing what we think it should do, which is to search for a node named "orange", of which there are none, and so an empty NodeSet is returned. We could make it return a non-empty NodeSet by searching for existing nodes:

```
puts Nokogiri::HTML.fragment(html).xpath("orange").inspect # => []
puts Nokogiri::HTML.fragment(html).xpath("p")
# => <p>Hello dear</p>
     <p class="orange">Yataaa</p>
```

I hope this was as fun and enlightening for you as it was for me.
