### ISSUE TITLE
Whitespace Treated

### ISSUE THREAD

**Issue by EngineeredEdge** [sparklemotion/nokogiri#1415]
test.xml
```
<link>
  <actor>Carrie Fisher</actor>
  <movie>Under the Rainbow (1981)</movie>
  <actor>Chevy Chase</actor>
  <movie>Doogal (2006)</movie>
  <actor>Ian McKellen</actor>
</link>
```

test.rb
```
require 'nokogiri' 

xml = File.read 'test.xml'
doc = Nokogiri::XML(xml)
children1 = doc.xpath('link/*')
children2 = doc.xpath('link').children

print children1.map(&:text)
puts
print children2.map(&:text)
puts
puts children1 == children2
```

$ruby test.rb
```
["Carrie Fisher", "Under the Rainbow (1981)", "Chevy Chase", "Doogal (2006)", "Ian McKellen"]
["\n  ", "Carrie Fisher", "\n  ", "Under the Rainbow (1981)", "\n  ", "Chevy Chase", "\n  ", "Doogal (2006)", "\n  ", "Ian McKellen", "\n"]
false
```

children1 behaves as I'd expect. children2 picks up newline and whitespace elements.

If this is intended behaviour and not in fact a bug, then I apologize for wasting your time.

**Comment by windwiny** [comment]
XML has some options.

    doc = Nokogiri::XML(xml) { |cfg| cfg.noblanks }

**Comment by flavorjones** [comment]
To better understand what you're seeing, let's use `#to_xml` instead of `#text` to map the children:

```
["<actor>Carrie Fisher</actor>", "<movie>Under the Rainbow (1981)</movie>", "<actor>Chevy Chase</actor>", "<movie>Doogal (2006)</movie>", "<actor>Ian McKellen</actor>"]
["\n  ", "<actor>Carrie Fisher</actor>", "\n  ", "<movie>Under the Rainbow (1981)</movie>", "\n  ", "<actor>Chevy Chase</actor>", "\n  ", "<movie>Doogal (2006)</movie>", "\n  ", "<actor>Ian McKellen</actor>", "\n"]
```

Specifically, you can see here that the xpath query `link/*` returns tags, and not text nodes. But calling `#children` on link will return *all* children, including text nodes.

The XPath spec actually helps us understand why this is the case:

https://www.w3.org/TR/xpath/#location-paths

indicates that:

> child::* selects all __element__ children of the context node

(emphasis mine).
