### ISSUE TITLE
Serialization inconsistency between jruby and mri implementations

### ISSUE THREAD

**Issue by hmarr** [sparklemotion/nokogiri#1420]
When using MRI, serializing an `XML::Document` results in a terminating newline character (LF). When using JRuby, the newline isn't present.

Really minor issue, but cost us a bit of time when porting an app to JRuby!

**ruby 2.2.2p95**

```ruby
irb(main):001:0> Nokogiri::XML("<foo/>").to_xml
=> "<?xml version=\"1.0\"?>\n<foo/>\n"
```

**jruby 9.0.4.0 (2.2.2)**
```ruby
irb(main):001:0> Nokogiri::XML("<foo/>").to_xml
=> "<?xml version=\"1.0\"?>\n<foo/>"
```

Tested with Nokogiri v1.6.7.2.

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question.

The reason serialization is inconsistent is because Nokogiri uses different libraries for MRI and JRuby. On MRI, we use libxml2; and on JRuby we use xerces+nekohtml.

We've made a lot of effort to try to make output consistent, but have no plans to address this particular inconsistency at this time.

If what you're looking for is identical, comparable output, please take a look at Document#canonicalize:

http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Document:canonicalize

If you're looking to compare pieces of a document, perhaps consider using CSS or XPath queries to assert on more specific aspects of your document.

I'm going to close this, but please feel free to continue the conversation here if you like, I'd love to help.

**Comment by hmarr** [comment]
Ok, thanks for the fast response - makes sense.
