### ISSUE TITLE
Nokogiri and mini_portile2, on old nokogiri version

### ISSUE THREAD

**Issue by jonathanstiansen** [sparklemotion/nokogiri#1434]
Preface: I'm using ruby 1.8.7, I know it's not supported but I'm also using a version of nokogiri that worked just fine before.
So when I add `'gem 'nokogiri', '~> 1.3', '>= 1.3.1'" ` to my Gemfile I get this error:

```ruby
Gem::InstallError: mini_portile2 requires Ruby version >= 1.9.2.
An error occurred while installing mini_portile2 (2.0.0), and Bundler cannot
continue.
Make sure that `gem install mini_portile2 -v '2.0.0'` succeeds before bundling.
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 5
```

Minimal Gemfile is this: source 

```ruby
'https://rubygems.org'
gem 'rails', '2.2.3'
gem 'nokogiri', '~> 1.3', '>= 1.3.1'
```

When I run `gem install mini_portile2 -v '2.0.0'` I get the obvious, needs ruby 1.9.3 to continue. 
I don't want to (can't) use ruby 1.9.3 until I get this setup. Why is it that somehow this old version of nokogiri tries to satisfy it's dependancy with a new dependancy. Also is there a good way to figure out which of nokogiri's dependancies requires this?

Thank you! And sorry if this is not constructive to most people :-(

**Comment by larskanis** [comment]
You must set the version constraint to "<1.6" in addition for Ruby 1.8.7.

**Comment by flavorjones** [comment]
@jonathanstiansen, thanks for asking this question.

@larskanis is correct. You're trying to install a more recent version of Nokogiri, because your gemspec constraints aren't tight enough.

You should be able to see this if you compare your previously installed version of Nokogiri (it'll be a 1.3.x, 1.4.x, or 1.5.x release) against what's being downloaded above.

I'm closing this issue, but please do let us know if you have further troubles.
