### ISSUE TITLE
Regular expression error

### ISSUE THREAD

**Issue by cryuff** [sparklemotion/nokogiri#1446]
I'm making verification xml against xsd and every regular expressions in xsd works well, except from one:
Element '{http://www.mf.gov.pl/xsd/ECS/IE515_v1-0.xsd}IE515', attribute 'EmailPodmiotu': [facet 'pattern'] The value 'testecs@huzar.pl' is not accepted by the pattern '[A-Za-z0-9]+((\.|-|_)[A-Za-z0-9]+)*(@[A-Za-z0-9]+((\.|-|_)[A-Za-z0-9]+)*){1}'.

Can you help me with fixing it?

**Comment by flavorjones** [comment]
Can you please provide a complete working example demonstrating what you're
seeing? This would help the maintainers diagnose the underlying cause.

Please see http://stackoverflow.com/help/mcve for guidance. Thank you!
On Mar 21, 2016 5:51 AM, "Kacper" <notifications@github.com> wrote:

I'm making verification xml against xsd and every regular expressions in
xsd works well, except from one:
Element '{http://www.mf.gov.pl/xsd/ECS/IE515_v1-0.xsd}IE515', attribute
'EmailPodmiotu': [facet 'pattern'] The value 'testecs@huzar.pl' is not
accepted by the pattern '[A-Za-z0-9]+((.|-|
*)[A-Za-z0-9]+)*(@[A-Za-z0-9]+((.|-|*)[A-Za-z0-9]+)*){1}'.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/sparklemotion/nokogiri/issues/1446>

**Comment by cryuff** [comment]
Ok so here are xml and xsd file:
https://www.dropbox.com/s/l38z10omuaa1hcq/noko.zip?dl=0

So now in my app i make xml: 
`  doc = Nokogiri::XML(Content.of.xml)`

Then i make xsd:
` xsd = Nokogiri::XML::Schema(Content.of.schema)`

Then i validate xml againt xsd:
xsd.validate(doc).each do |er|

and in this particular case for xml and xsd from dropbox i get:
`Element '{xxx}IE515', attribute 'EmailPodmiotu': [facet 'pattern'] The value 'ema@email.com' is not accepted by the pattern '[A-Za-z0-9]+((\.|-|_)[A-Za-z0-9]+)*(@[A-Za-z0-9]+((\.|-|_)[A-Za-z0-9]+)*){1}'.`

and i think that regular expression is correct, value is also correct, so i don't know why the error appers.

**Comment by cryuff** [comment]
Ok i find error already, error was in schema.

**Comment by flavorjones** [comment]
Ok, good to know!
