### ISSUE TITLE
Throw a more specific error for an empty document

### ISSUE THREAD

**Issue by newellista** [sparklemotion/nokogiri#1448]
When an empty document gets returned, would it be possible to throw a more specific error?

The current code (https://github.com/sparklemotion/nokogiri/blob/master/ext/java/nokogiri/XmlSaxParserContext.java#L263-L264) throws a `RuntimeError`.  Could you return something like `EmptyDocumentError < RuntimeError`?  

We are occasionally running into a problem, where our upstream API provider is sending an empty XML document.  Rather than rescuing `RuntimeError` and then parsing the error message, it would be more idiomatic to be able to rescue something like `EmptyDocumentError`.

**Comment by flavorjones** [comment]
I'd prefer to raise a SyntaxError, as we've standardized the XML DOM strict parsing on MRI and JRuby to do this (see #1005 for details).

I think that will have to suffice, since I don't believe the SAX parser errors differentiate between an empty document and a set of other invalid-document errors.

Objections to that solution?

**Comment by newellista** [comment]
I suppose that works.  My main objection is to `RuntimeError`, so this would certainly be an improvement!

Thanks for the reply/consideration!

**Comment by flavorjones** [comment]
I think this was fixed in commit aece1ef which was in 1.6.8.
