### ISSUE TITLE
please update OSX Installation guide

### ISSUE THREAD

**Issue by haifengkao** [sparklemotion/nokogiri#1462]
The installation guide at http://www.nokogiri.org/tutorials/installing_nokogiri.html doesn't work for OSX El Capitan anymore. Would you please update it?
You can find relevant discussions at http://stackoverflow.com/a/23584954/912645

**Comment by flavorjones** [comment]
Hi,

I'm sorry you found the installation guide lacking. Can you be more specific about what error you encountered that wasn't addressed by the steps in the guide?

The SO comment you link to isn't clear enough for me to understand the problem, the recommended solution, and the documentation gap.

Alternatively, you could submit a PR to the documentation directly:

> https://github.com/sparklemotion/nokogiri.org-tutorials

**Comment by jasonbodily** [comment]
I get the following on El Capitan:

ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
/Users/jb/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160426-3474-vip6j.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
Using mini_portile version 2.0.0
checking for iconv.h... yes
checking for gzdopen() in -lz... yes
checking for iconv using --with-opt-* flags... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.2
with the following patches applied:
	- 0001-Revert-Missing-initialization-for-the-catalog-module.patch
	- 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
	- 0003-Stop-parsing-on-entities-boundaries-errors.patch
	- 0004-Cleanup-conditional-section-error-handling.patch
	- 0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch
	- 0006-Another-variation-of-overflow-in-Conditional-section.patch
	- 0007-Fix-an-error-in-previous-Conditional-section-patch.patch
	- 0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch
	- 0009-Updated-config.guess.patch
	- 0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
	- 0011-Avoid-extra-processing-of-MarkupDecl-when-EOF.patch
	- 0012-Avoid-processing-entities-after-encoding-conversion-.patch
	- 0013-CVE-2015-7497-Avoid-an-heap-buffer-overflow-in-xmlDi.patch
	- 0014-CVE-2015-5312-Another-entity-expansion-issue.patch
	- 0015-Add-xmlHaltParser-to-stop-the-parser.patch
	- 0016-Detect-incoherency-on-GROW.patch
	- 0017-CVE-2015-7500-Fix-memory-access-error-due-to-incorre.patch
	- 0018-CVE-2015-8242-Buffer-overead-with-HTML-parser-in-pus.patch
	- 0019-Do-not-print-error-context-when-there-is-none.patch
	- 0020-xmlStopParser-reset-errNo.patch
	- 0021-Reuse-xmlHaltParser-where-it-makes-sense.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.2.tar.gz into tmp/x86_64-apple-darwin15.3.0/ports/libxml2/2.9.2... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0001-Revert-Missing-initialization-for-the-catalog-module.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0003-Stop-parsing-on-entities-boundaries-errors.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0004-Cleanup-conditional-section-error-handling.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0006-Another-variation-of-overflow-in-Conditional-section.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0007-Fix-an-error-in-previous-Conditional-section-patch.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0009-Updated-config.guess.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0011-Avoid-extra-processing-of-MarkupDecl-when-EOF.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0012-Avoid-processing-entities-after-encoding-conversion-.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0013-CVE-2015-7497-Avoid-an-heap-buffer-overflow-in-xmlDi.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0014-CVE-2015-5312-Another-entity-expansion-issue.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0015-Add-xmlHaltParser-to-stop-the-parser.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0016-Detect-incoherency-on-GROW.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0017-CVE-2015-7500-Fix-memory-access-error-due-to-incorre.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0018-CVE-2015-8242-Buffer-overead-with-HTML-parser-in-pus.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0019-Do-not-print-error-context-when-there-is-none.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0020-xmlStopParser-reset-errNo.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxml2/0021-Reuse-xmlHaltParser-where-it-makes-sense.patch... OK
Running 'configure' for libxml2 2.9.2... OK
Running 'compile' for libxml2 2.9.2... OK
Running 'install' for libxml2 2.9.2... OK
Activating libxml2 2.9.2 (from /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ports/x86_64-apple-darwin15.3.0/libxml2/2.9.2)...
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxslt-1.1.28
with the following patches applied:
	- 0001-Adding-doc-update-related-to-1.1.28.patch
	- 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
	- 0003-Initialize-pseudo-random-number-generator-with-curre.patch
	- 0004-EXSLT-function-str-replace-is-broken-as-is.patch
	- 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
	- 0007-Separate-function-for-predicate-matching-in-patterns.patch
	- 0008-Fix-direct-pattern-matching.patch
	- 0009-Fix-certain-patterns-with-predicates.patch
	- 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
	- 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
	- 0014-Fix-for-bug-436589.patch
	- 0015-Fix-mkdir-for-mingw.patch
	- 0016-Fix-for-type-confusion-in-preprocessing-attributes.patch
	- 0017-Updated-config.guess.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install
************************************************************************
Extracting libxslt-1.1.28.tar.gz into tmp/x86_64-apple-darwin15.3.0/ports/libxslt/1.1.28... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0001-Adding-doc-update-related-to-1.1.28.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0003-Initialize-pseudo-random-number-generator-with-curre.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0004-EXSLT-function-str-replace-is-broken-as-is.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0006-Fix-str-padding-to-work-with-UTF-8-strings.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0007-Separate-function-for-predicate-matching-in-patterns.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0008-Fix-direct-pattern-matching.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0009-Fix-certain-patterns-with-predicates.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0014-Fix-for-bug-436589.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0015-Fix-mkdir-for-mingw.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0016-Fix-for-type-confusion-in-preprocessing-attributes.patch... OK
Running git apply with /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/patches/libxslt/0017-Updated-config.guess.patch... OK
Running 'configure' for libxslt 1.1.28... OK
Running 'compile' for libxslt 1.1.28... OK
Running 'install' for libxslt 1.1.28... OK
Activating libxslt 1.1.28 (from /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ports/x86_64-apple-darwin15.3.0/libxslt/1.1.28)...
checking for main() in -llzma... yes
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jb/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/mkmf.log

current directory: /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
make "DESTDIR=" clean

current directory: /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
make "DESTDIR="
compiling html_document.c
couldn't understand kern.osversion `15.3.0'
cc1: error: unrecognized command line option "-Wdivision-by-zero"
make: *** [html_document.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2 for inspection.
Results logged to /Users/jb/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/gem_make.out
`

When I run the following: 

bundle config build.nokogiri --use-system-libraries
bundle install

I get

`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
/Users/jb/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160426-26191-1fhai4h.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jb/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-libxslt-config
	--without-libxslt-config
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-libexslt-config
	--without-libexslt-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jb/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/jb/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2 for inspection.
Results logged to /Users/jb/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/gem_make.out`

And then I cat /Users/jb/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/mkmf.log and I get:

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jbodily/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
/Users/jbodily/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160426-47943-1x88fba.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jbodily/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-libxslt-config
	--without-libxslt-config
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-libexslt-config
	--without-libexslt-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jbodily/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/jbodily/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2 for inspection.
Results logged to /Users/jbodily/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.7.2/gem_make.out`

and updating rubygems 2.4.5 doesn't help.

**Comment by haifengkao** [comment]
done. see https://github.com/sparklemotion/nokogiri.org-tutorials/pull/47
