### ISSUE TITLE
http://www.nokogiri.org/tutorials/installing_nokogiri.html

### ISSUE THREAD

**Issue by fulldecent** [sparklemotion/nokogiri#1620]
This documentation explains how to install build prerequisites for Nokogiri. BUT IT LEAVES OUT THE MOST IMPORTANT ONES.

Please also include documentation for Linux Mint or similar for how to install the system library packages that Nokogiri needs with NOKOGIRI_USE_SYSTEM_LIBRARIES.

We found `libxml2` but `libxslt` is not a valid package on Linux Mint.

**Comment by fulldecent** [comment]
This worked for me: 

    sudo apt-get install ruby-dev build-essential libxml2 libxslt-dev

**Comment by flavorjones** [comment]
@fulldecent I'd love if you could submit a PR to the tutorial for this, rather than suggest it here. I'm under water and maintaining this alone, and the few minutes that would save me would be greatly appreciated.

That repo is https://github.com/sparklemotion/nokogiri.org-tutorials

Thanks so much.
