### ISSUE TITLE
A tag can not include TABLE tag.

### ISSUE THREAD

**Issue by tashua314** [sparklemotion/nokogiri#1638]
Action: 
```
Nokogiri::HTML::DocumentFragment.parse('<a><table></table></a>').to_html
```

Output (Expected):
```
<a><table></table></a>
```

Output (Actual):
```
<a></a><table></table>
```

**Comment by ar7max** [comment]
Mb cuz <a> is an inline element, however <p> is a block-level element and result is the same

**Comment by flavorjones** [comment]
Hi @tashua314,

Thanks for asking this question.

Neither the `<a>` nor the `<p>` elements can contain block-level elements as children. See https://www.w3.org/TR/html4/struct/links.html#edef-A and https://www.w3.org/TR/html4/struct/text.html#edef-P to see that these are both inline elements.

To wit:

```
The P element represents a paragraph. It cannot contain block-level elements (including P itself).
```

I think you'll find that if you change `<a>` to a block-level element like `<div>` that this works as expected.

The behavior you're seeing is libxml2 attempting to correct invalid markup (much as browsers do) by following some simple rules. In this case, because a `table` can't be contained in an `a` tag, the `a` tag is closed before the `table` is opened.

Hope this helps!

**Comment by tashua314** [comment]
Thank you for the reply, @flavorjones .

I have another question.
HTML5 seems to be allowed to add block-level elements to <a> tags.
Is this excluded?
https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element

**Comment by flavorjones** [comment]
Sorry, Nokogiri's parser doesn't support HTML5. You can try the Nokogumbo
project, which extends Nokogiri to support HTML5.
