### ISSUE TITLE
Base URI not set correctly for xincludes with File.read or URLs

### ISSUE THREAD

**Issue by rcrews** [sparklemotion/nokogiri#1644]
Base URI is not set correctly for xincludes with File.read or opening a URL.
The following examples assume the GitHub nokogiri repo is cloned to /Users/rcrews/Sandbox/nokogiri. Should be easy to adapt to whatever path yours is cloned to.

This fails when run from the Desktop (such as /Users/rcrews/Desktop):

```ruby
require 'nokogiri'
file = '/Users/rcrews/Sandbox/nokogiri/test/files/xinclude.xml'
doc = Nokogiri::XML(File.read(file)) { |conf| conf.xinclude }
puts doc.to_s
```

But it works if I Dir.chdir to the directory of the XML so the URIs are
relative to the current directory:

```ruby
require 'nokogiri'
file = '/Users/rcrews/Sandbox/nokogiri/test/files/xinclude.xml'
Dir.chdir('/Users/rcrews/Sandbox/nokogiri/test/files')
doc = Nokogiri::XML(File.read(file)) { |conf| conf.xinclude }
puts doc.to_s
```

It does work fine if I first File.open (from the Desktop):

```ruby
require 'nokogiri'
file = '/Users/rcrews/Sandbox/nokogiri/test/files/xinclude.xml'
doc = nil
File.open(file) do |fp|
  doc = Nokogiri::XML(fp) { |conf| conf.xinclude }
end
puts doc.to_s
```

But it again fails when I try to read from a URL:

```ruby
require 'nokogiri'
require 'open-uri'
url = 'https://raw.githubusercontent.com/sparklemotion/nokogiri/master/test/files/xinclude.xml'
doc = Nokogiri::XML(open(url)) { |conf| conf.xinclude }
puts doc.to_s
```

or alternately...

```ruby
require 'nokogiri'
require 'open-uri'
url = 'https://raw.githubusercontent.com/sparklemotion/nokogiri/master/test/files/xinclude.xml'
doc = nil
open(url) do |fp|
  doc = Nokogiri::XML(fp) { |conf| conf.xinclude }
end
puts doc.to_s
```

Interestingly, it does work if I first cd to the local directory where the content resides. (Yikes! It's resolving the remote file xinclude to a local file!)

```ruby
require 'nokogiri'
require 'open-uri'
url = 'https://raw.githubusercontent.com/sparklemotion/nokogiri/master/test/files/xinclude.xml'
Dir.chdir('/Users/rcrews/Sandbox/nokogiri/test/files')
doc = Nokogiri::XML(open(url)) { |conf| conf.xinclude }
puts doc.to_s
```

**Comment by flavorjones** [comment]
Thanks for the verbose description of what you're seeing. I'll take a look.

**Comment by flavorjones** [comment]
@rcrews Apologies again for the slow reply.

When calling `Nokogiri::XML(File.read(file))` there's no way for Nokogiri to know the base URI since `IO.read` [returns a string](https://ruby-doc.org/core-2.5.0/IO.html#method-c-read). In this use case, you should pass in the path as the second argument to `XML()` or `XML::Document.parse()`:

```ruby
file = '/home/flavorjones/code/oss/nokogiri/test/files/xinclude.xml'
doc = Nokogiri::XML(File.read(file), file) { |conf| conf.xinclude }
```

When you pass a file descriptor, such as that yielded by `File.open`, Nokogiri will check if the object responds to `path`, and if so will use that as the base URI.

OpenURI's `Kernel.open`, though, returns a `StringIO` object which, similar to the `String` returned by `File.read`, does not respond to `path` and so Nokogiri won't know how to handle this. Again, you should be able to pass the URI as the second argument:

```ruby
doc = Nokogiri::XML(open(url), url) { |conf| conf.xinclude.nononet }
```

and you'll see the error message now displays the right uri:

```
ERROR: could not load https://raw.githubusercontent.com/sparklemotion/nokogiri/master/test/files/to_be_xincluded.xml, and no fallback was found
```

It's not immediately obvious to me why I can't get that URI to be xincluded, but it's not relevant to the original question you asked.

I hope this helps?
