### ISSUE TITLE
Release Windows fat gem for Ruby 2.5

### ISSUE THREAD

**Issue by Hazardius** [sparklemotion/nokogiri#1706]
Just a notice about issue with nokogiri fat gem 1.8.1 on Windows machines.
Current release informs about ruby version not being <2.5 .
Will it be supported with a new release - 1.8.2?

Issue name based on #1618 .

**Comment by 3rdmaths** [comment]
I'm also interested in such support, the latest 2.5 version of ruby is assumed to have many time optimization and some syntaxical sugar that can help to improve code readability.

The only non backward change that I can find is https://bugs.ruby-lang.org/issues/11547, but it shouldn't impact any well written code. In my opinion, reference to a variable in a namespace should not assume that it can be defined at top level rather than in the namespace context.

**Comment by Hazardius** [comment]
EDIT 2018-01-04:
As above - sorry that I didn't checked pull requests. Closing the issue as it's already waiting there at #1704.
