### ISSUE TITLE
chore: go through generated rdocs and review formatting and doc strings

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1848]
My hunch is that we haven't looked at the generated rdocs in a long time, and I'm spotting things like `VersionInfo` showing up despite having a `:nodoc:` declaration. Simultaneously, the `VERSION` constant doesn't show up, where I expected it to.

Let's set aside some time to review https://www.rubydoc.info/github/sparklemotion/nokogiri and find and fix some of those broken windows.

**Comment by klandergren** [comment]
@flavorjones I looked into this and found out the following (which you may already be aware of):

> ...showing up despite having a `:nodoc:` declaration

I think this is because rubydoc.info uses [yard](https://github.com/lsegal/yard), which does not support `:nodoc:` out of the box:

https://rubydoc.tenderapp.com/kb/getting-started-with-rubydocinfo/where-is-my-nodoc

grepping through `nokogiri/lib` there are some instances of `@private` use, but not as widespread as `:nodoc:` :

```bash
$ grep -r '@private' ./lib/ | wc -l
       3
$ grep -r ':nodoc:' ./lib/ | wc -l                                                                             
      28
```
so if nokogiri actually wants to hide these instances on rubydoc.info they would need updating to yard tags, and include  yardopt of `--no-private`

note: spot checking locally generated `rdoc` does correctly produce the documentation you would expect:

```bash
$ rdoc lib
$ ruby -run -e httpd ./doc -p 9090 
```
I briefly searched for an yardopt to fully support rdoc tags without luck

> ...fix some of those broken windows.

I am not sure what you meant here—didn't look into it.

**so tl; dr:** some options to consider:

- support both. pros: rdoc and yard users both happy. cons: although yard is a superset of rdoc, it may be difficult to have consistent presentation between both without some case-by-case workarounds
- standardize on yard tags. pros: more expressive documentation. yard features. better rubydoc.info presentation (caveat: comes with the yard private documentation philosophy). cons: ensuring rdoc users have useable documentation. losing rdoc features I am not aware of?
- standardize on rdoc. pros: simple / already supported in code base. cons: live with worse rubydoc.info presentation
- freeze rdoc usage, use yard going forward
- something else?

I recommend figuring out the main use case for nokogiri's documentation and choosing the best option based on that.

**Comment by flavorjones** [comment]
@klandergren Thank you for spending time looking into this! I really appreciate your expertise, because I know next-to-nothing about Yard. Lots to think about here.
