### ISSUE TITLE
Nokogiri delivers some weird parsing results with malformed XML (&gt; disappears)

### ISSUE THREAD

**Issue by nobletrout** [sparklemotion/nokogiri#1856]
I was trying to chase down a nasty issue, and came up against a bunch of google search results. Ended being caused by malformed XML that Noko was still parsing and returning on. It's because of multiple declarations. Not sure if it's a bug or what, but I would expect the parser to ignore additional declarations rather than change output.

The following code:

```
require 'nokogiri'
xml_doc =<<HERE
<?xml version="1.0"?>
<node1>
<?xml version="1.0"?>
<node2>
some text with &gt; and &lt; and &quot; and &#x41; &#x3C; done
</node2>
</node1>
HERE

puts Nokogiri::XML(xml_doc).to_xml
```

returns:
```
<?xml version="1.0"?>
<node1>
<?xml version="1.0"?>
<node2>
some text with  and  and  and A &lt; done
</node2>
</node1>
```

**Comment by flavorjones** [comment]
Hi there! Thanks for asking this question. I've reproduced this behavior running Nokogiri 1.10.0 with libxml 2.9.9.

Looking at the structure of the document reveals:

```
#! /usr/bin/env ruby

require 'nokogiri'
xml_doc =<<HERE
<?xml version="1.0"?>
<node1>
<?xml version="1.0"?>
<node2>
some text with &gt; and &lt; and &quot; and &#x41; &#x3C; done
</node2>
</node1>
HERE

doc = Nokogiri::XML(xml_doc)
doc.inspect
# => "#<Nokogiri::XML::Document:0x2b20aadb0024 name=\"document\" children=[#<Nokogiri::XML::Element:0x2b20aae33b90 name=\"node1\" children=[#<Nokogiri::XML::Text:0x2b20aae339d8 \"\\n\">, #<Nokogiri::XML::ProcessingInstruction:0x2b20aae338d4 name=\"xml\">, #<Nokogiri::XML::Text:0x2b20aae33708 \"\\n\">, #<Nokogiri::XML::Element:0x2b20aae33654 name=\"node2\" children=[#<Nokogiri::XML::Text:0x2b20aae3349c \"\\nsome text with  and  and  and A < done\\n\">]>, #<Nokogiri::XML::Text:0x2b20aae332f8 \"\\n\">]>]>"

doc.errors.inspect
# => "[#<Nokogiri::XML::SyntaxError: 3:6: FATAL: XML declaration allowed only at the start of the document>]"
```

I'll repeat here the interesting bit: `#<Nokogiri::XML::ProcessingInstruction:0x2b20c65583b0 name="xml">`

You can read up on Processing Instructions here: https://en.wikipedia.org/wiki/Processing_Instruction

So in summary, the second declaration is being interpreted by libxml2 as a Processing Instruction ("PI") which is identical in syntax to the XML Declaration as noted in the [wikipedia entry](https://en.wikipedia.org/wiki/Processing_Instruction#Syntax).

You might also note that libxml2 detects that this is probably a misplaced XML declaration, but because the default is to parse-and-recover, it does its best to "fix it" and is still generating a valid, well-formed document by ensuring it appears as a PI.

Additionally, I'll note that this behavior is inherited from the underlying parsing engine, and so there's nothing Nokogiri can easily to do change this. If you feel strongly that this is something that should be changed, I encourage you to bring it up on the upstream libxml2 mailing list.

I hope this helps?

**Comment by nobletrout** [comment]
yes, thanks. I know it's an invalid syntax, I just thought the behavior was sufficiently weird that someone else searching the Internet might get saved a few hours of figuring out what is going wrong. I'll notify the upstream project.
