### ISSUE TITLE
Confusion when building native static nokogiri extension on OS X High Sierra.

### ISSUE THREAD

**Issue by androbtech** [sparklemotion/nokogiri#1907]
Ruby 2.6.3p62

I've been trying many ways to build the gem.

If I run `gem install nokogiri -- --with-iconv-dir=/path/to/iconv` it fails to generate the makefile (the error shows up when building the second packaged version libxslt 1.1.3.3) and the logs show [something like this ](https://gist.github.com/androbtech/b053bf8a8e7389c15121b753fa003ef7)

However, if I install with `gem install nokogiri -- --with-opt-dir=/path/to/iconv` I can successfully build.

`otool -L nokogiri.bundle 
/2.6.0/gems/nokogiri-1.10.3/ext/nokogiri/nokogiri.bundle:
      /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)`

Could this be the culprit? (https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L396)

Versions before this one I had trouble installing Nokogiri because it had a hardcoded path for iconv and it would abort the build process if such file wasn't present (versions of nokogiri way older). I've invested hours on this and can't seem to find an ideal solution yet.

**Comment by flavorjones** [comment]
Hi. Thanks for asking this question, and sorry you're having trouble.

Because you haven't used the Issue template for reporting installation issues, I need a bit more information to help diagnose what's going on. I'll paste the questions below, please try to answer them when you have a moment?

---

**Have you read and followed the advice in the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

Please make sure the escape the file contents with triple-backticks.


**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

Please make sure the escape the file contents with triple-backticks.


**What operating system are you using?**

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

If MacOS, please note the version of XCode you have installed.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

If Windows, please note whether you're installing the precompiled gems, or compiling yourself with DevKit. Also please note the version of RubyInstaller you've installed.

**Comment by androbtech** [comment]
I will revisit the problem after I finish working on other extension gems that I need to build statically and see if I find the problem and perhaps do a PR on it. I tried before but stopped after reading the reasons why there is no gemspec and I needed to move forward quickly.

I will generate a nokogiri gemspec to investigate further.
