### ISSUE TITLE
XML parsing fails for special charatcters

### ISSUE THREAD

**Issue by kapso** [sparklemotion/nokogiri#1929]
Nokogiri is failing for XML documents that have these characters - `&`, `<` and `>`

`Nokogiri::XML::SyntaxError -- 231:574: FATAL: StartTag: invalid element name`

Is there a fix for this?

**Comment by flavorjones** [comment]
Hi! I'd like to help, but I need more information. Here's what I did to try to reproduce:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

xml = "<root>123 < 234</root>"

doc = Nokogiri::XML(xml)
puts doc
# => <?xml version="1.0"?>
#    <root>123  234</root>

puts doc.errors
# => 1:12: FATAL: StartTag: invalid element name
```

You can see that the parse succeeds, and Nokogiri silently stores the error message in `#errors`.

-----

You must have missed the bug report template, so I'd like to ask you to provide us with that information:

**Describe the bug**

A clear and concise description of what the bug is. Please include as much context as you can about what you are trying to do.


**To Reproduce**

If possible, please include a complete, self-contained script that reproduces the behavior you're seeing. Please try to remove external dependencies like Rails or other libraries that may be wrapping Nokogiri.

Here's an example of how you might structure such a script:

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Node#css" do
    it "should find a div using chained classes" do
      html = <<~HEREDOC
        <html>
          <body>
            <div class="foo"> one</div> 
            <div class="bar">two</div> 
            <div class="foo bar">three</div> 
      HEREDOC
      
      doc = Nokogiri::HTML::Document.parse(html)
      
      assert_equal 1, doc.css("div.foo.bar").length
      assert_equal "three", doc.at_css("div.foo.bar").text
    end
  end
end
```

If you haven't included a test, please provide whatever code you can, the inputs if any, along with the output that you're seeing. We need to reproduce what you're seeing to be able to help.


**Expected behavior**

If you haven't included a test above, please tell us precisely what you expected to happen.


**Environment**

Please paste the output from `nokogiri -v` here, escaped by triple-backtick.

This output will tell us what version of Ruby you're using, how you installed nokogiri, what versions of the underlying libraries you're using, and what operating you're using.


**Additional context**

Add any other context about the problem here.

**Comment by kapso** [comment]
@flavorjones thanks for the response, and this helps.

Looks like the difference is that I am using `Nokogiri::XML::ParseOptions::STRICT` when parsing XML, while the default seems to be `Nokogiri::XML::ParseOptions::DEFAULT_XML` from the code here - https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml.rb#L34

I am actually using this Gem to parse XML docs, and they use `Nokogiri::XML::ParseOptions::STRICT` when parsing XML document - 
https://github.com/mvz/happymapper/blob/master/lib/happymapper.rb#L307
