### ISSUE TITLE
Nokogiri is not working/installing properly on Mac OS X 10.15 Catalina

### ISSUE THREAD

**Issue by eltherion** [sparklemotion/nokogiri#1933]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

YES.

**What is the complete output of `gem install`?**
```
$ gem install nokogiri
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.4
Parsing documentation for nokogiri-1.10.4
Done installing documentation for nokogiri after 1 seconds
1 gem installed
```

**What operating system are you using?**

Mac OS X 10.15 Catalina 
Xcode 11.1

After (successful?) installation:
```
$ bundle install |grep nokogiri
Using nokogiri 1.10.4
Using nokogiri-pretty 0.1.0
```
And then:
```
$ rails s
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
[...] above repeated many times
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring bcrypt-3.1.13 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.13
Ignoring bootsnap-1.4.5 because its extensions are not built. Try: gem pristine bootsnap --version 1.4.5
Could not find nokogiri-1.10.4 in any of the sources
Run `bundle install` to install missing gems.
```

So we are back to the starting point.

**Comment by danestreet-jwilliams** [comment]
It's giving me the same issue as well

**Comment by josegrad** [comment]
Same issue. Any progress?

**Comment by josegrad** [comment]
This pointed me in the right direction:

[https://stackoverflow.com/questions/5528839/why-does-installing-nokogiri-on-mac-os-fail-with-libiconv-is-missing](url)

**Comment by flavorjones** [comment]
@josegrad the post you link to is related to installation-time problems, but the OP is asking about a runtime problem.

@eltherion I'm afraid I've never seen this issue before. I will note, though, that the issue doesn't seem to be specific to Nokogiri, as bcrypt also emits this warning. Notably, what Nokogiri and bcrypt have in common is compiled C extensions.

You may want to look into how Ruby is installed on your machine, and perhaps as on a wider forum like ruby-talk to see if anyone has a) seen this before, b) ideas on how to debug it, and c) a solution.

If I was seeing this, I'd probably uninstall ruby and re-install it; because if compiled C extensions are working at installation time, but not found at runtime, this is likely an environmental issue (e.g., directories in the lookup paths, file extensions, etc.).

I'd like to leave this open for now, so we can talk about it and try to close the loop for people who have this problem in the future. But at the moment, I'm at a bit of a loss with what to advise beyond what I've said above.

**Comment by eltherion** [comment]
Clean reinstall of ruby environment + updating Xcode and running `xcode-select --install` finally helped. I hope it will work for you guys as well.
