### ISSUE TITLE
parse XSLT::Stylesheet using the libxslt-preferred options

### ISSUE THREAD

**Issue by menafkasap** [sparklemotion/nokogiri#1940]
The content in CDATA isn't affected by `disable-output-escaping`

Two files shared below don't produce the same output with xsltproc and nokogiri.

### FILES
`test.xsl`
```xsl
<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" omit-xml-declaration="yes" />
    <xsl:template match="/">
        <xsl:text disable-output-escaping="yes"><![CDATA[<>]]>
</xsl:text>
    </xsl:template>
</xsl:stylesheet>
```
-----------------------
`test.xml`
```xsl
<t></t>
```
-----------------------
`test.rb`
```ruby
#!/usr/bin/env ruby

require 'nokogiri'

xslt  = Nokogiri::XSLT(File.read(ARGV[0]))
xml = Nokogiri::XML(File.read(ARGV[1]))

puts xslt.transform(xml)
```

### OUTPUTS

`xsltproc test.xsl test.xml`
```
<>
```
-----------------------
`./test.rb test.xsl test.xml`
```
<?xml version="1.0"?>
&lt;&gt;
```

**Comment by flavorjones** [comment]
@menafkasap Thanks for reporting this issue, and apologies for my slow reply.

I've tracked this down to the parse options used for the XSL file. `xsltproc` uses the C constant `XSLT_PARSE_OPTIONS` (which is `NOENT | DTDLOAD | DTDATTR | NOCDATA`), while Nokogiri uses `XML::ParseOptions::DEFAULT_XML` (which is `RECOVER | NONET`). Specifically, the behavioral difference you're spotting is due to the presence/absence of `NOCDATA`.

I think what we should be doing here is using these same options for the XSL files within Nokogiri (e.g., in the `XSLT.parse` method).

**Comment by flavorjones** [comment]
PR submitted at #2221. Will land in v1.12.x.
