### ISSUE TITLE
can't install on ubuntu 18

### ISSUE THREAD

**Issue by jjb** [sparklemotion/nokogiri#1981]
On a pretty barebones ubuntu 18 instance running under Vagrant, I get this when installing 1.10.7

```
tar: libxml2-2.9.10/test/relaxng/ambig_name-class2.rng: Cannot hard link to ‘libxml2-2.9.10/test/relaxng/ambig_name-class.xml’: Operation not permitted
tar: libxml2-2.9.10/test/relaxng/ambig_name-class.rng: Cannot hard link to ‘libxml2-2.9.10/test/relaxng/tutorA.rng’: Operation not permitted
```

1.9.1 installs with no problem

Let me know any other info you need.

**Comment by jjb** [comment]
brightbox ruby 2.6.5

**Comment by flavorjones** [comment]
Hi @jjb, thanks for asking this question. When you opened an issue, you were prompted with an option for "Installation issues" -- this option prompts you for more information so that we can help.

I'll paste the template below. Please provide that info and we'll try to help out.

---

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

Please make sure to escape the file contents with triple-backticks.


**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

Please make sure to escape the file contents with triple-backticks.


**What operating system are you using?**

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

If MacOS, please note the version of XCode you have installed.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

If Windows, please note whether you're installing the precompiled gems, or compiling yourself with DevKit. Also please note the version of RubyInstaller you've installed.

**Comment by jjb** [comment]
sorry! 😅 

annnd now I can't replicate it. maybe something in the process of installing the lower version changed the environment somehow. i guess if no one else is having the issue the issue should be closed.
