### ISSUE TITLE
Convert mini_portile2 dependency to >= from ~>

### ISSUE THREAD

**Issue by darix** [sparklemotion/nokogiri#2033]
Or is there really a good reason to use ~> here?

**Comment by flavorjones** [comment]
Hi @darix, thanks for asking this question. We use the `~> M.m.p` operator because we want to keep Nokogiri locked to a minor version of mini_portile2. This has been important to avoiding certain edge cases during installation of Nokogiri (as mini_portile2 is actually an _installation time_ dependency, and not a _run time_ dependency, which is uncommon and perhaps unique).

Can I ask you to describe the problem you're having?

**Comment by darix** [comment]
well it seems the mini_portile2 api was quite stable over the last few releases so it didn't feel needed to lock it down that much. so when ever we update our mini_portile2 package to follow its development and allow users to use the latest version, we have to fork off a version mini_portile2 package to keep nokogiri building. So we thought we would at least ask if that could be changed. Especially as nokogiri upstream and mini_portile2 upstream are working together. :)

**Comment by flavorjones** [comment]
Hi @darix, thanks for responding. I'm still not sure I understand the problem you're trying to solve.

To rephrase what I said above: we lock Nokogiri to a specific mini_portile2 version in order to prevent a future breaking change in mini_portile2 from affecting older versions of Nokogiri.

**Comment by flavorjones** [comment]
Put another way: I know that Nokogiri v1.10.9 will install cleanly on a large variety of systems when it's installed with mini_portile2 version 2.5.x. I don't know for sure that Nokogiri 1.6.7 (released in 2015) will install cleanly with the same version of mini_portile2, because we don't test that combination. It *might* install, but why would I ask users to take on that risk?

**Comment by flavorjones** [comment]
@darix who are your users, can you tell me a bit more about what they're doing and why this is a problem for them?

**Comment by darix** [comment]
I am packaging rubygems for openSUSE. We do have that largely automated. That automation recently picked up your 2.5.0 update for our rubygem-mini_portile2. now we have to provide an additional package rubygem-mini_portile2-2.4 to keep nokogiri building as we don't have a release of nokogiri that supports 2.5 yet. And we try avoid to have multiple versions of the same code on the distribution. It is not a big issue but we thought we would at least ask. :)

**Comment by flavorjones** [comment]
Well, if it's helpful, you don't actually need mini_portile2 if you're building nokogiri against system libraries. It's an install-time dependency, and only if you're compiling the vendored libxml2/libxslt. I'd suggest that if you simply omit that dependency from the packaged nokogiri's dependencies, this would be fine.
