### ISSUE TITLE
package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in D:/install/Ruby27-x64/lib/ruby/gems/2.7.0/cache/nokogiri-1.11.0.rc2-x64-mingw32.gem

### ISSUE THREAD

**Issue by Ghostwritten** [sparklemotion/nokogiri#2039]
window10 64x

```
 ruby -v 
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
```
I want to install **nokogiri -v '1.11.0.rc2'**
```
$ gem install nokogiri -v '1.11.0.rc2' --source 'https://rubygems.org/'
Fetching nokogiri-1.11.0.rc2-x64-mingw32.gem
ERROR:  Error installing nokogiri:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in D:/install/Ruby27-x64/lib/ruby/gems/2.7.0/cache/nokogiri-1.11.0.rc2-x64-mingw32.gem
```
if I run:
```
$ gem install nokogiri
ERROR:  Error installing nokogiri:
        The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.10.9. Try installing it with `gem install nokogiri -v 1.10.9`      
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.1.83.
```

this is a bug? I can't solve the issuse ? 
Do I need to rollback **Ruby 2.7.0**?
help!

**Comment by eccobln** [comment]
Von meinem iPhone gesendet

**Comment by flavorjones** [comment]
Hi, sorry you're having problems, I'll try to help.

The first error message, "invalid gem: package is corrupt" is likely due to an incomplete or corrupted file downloaded (if you google for this phrase you'll see lots of hits, and this seems to be more common for larger gems -- and the Nokogiri windows gem file is quite large). Please remove your gem cache and try to re-download it.

The second error, "nokogiri requires Ruby version >= 2.3, < 2.7.dev", is because only release candidates support Ruby 2.7 precompiled on Windows. See https://github.com/sparklemotion/nokogiri/issues/2029 for background and for updates.

**Comment by eccobln** [comment]
Von meinem iPhone gesendet

**Comment by flavorjones** [comment]
Nokogiri v1.10.10 has been released with precompiled support for Ruby 2.7 on Windows.

**Comment by eccobln** [comment]
torsten wozniak
torsten@don-rondo.com <mailto:torsten@don-rondo.com>
www.don-rondo.com/Barbier <http://www.don-rondo.com/Barbier>

Office :+49302170909

**Comment by eccobln** [comment]
torsten wozniak
torsten@don-rondo.com <mailto:torsten@don-rondo.com>
www.don-rondo.com/Barbier <http://www.don-rondo.com/Barbier>

Office :+49302170909
