### ISSUE TITLE
libgcrypt.so.11 required by nokogiri 1.10.9 not found for centos 8

### ISSUE THREAD

**Issue by fmonvoisin** [sparklemotion/nokogiri#2060]
After migrating ruby application to centos 8, application won't start with following error :
.../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `require': libgcrypt.so.11: cannot open shared object file: No such file or directory - .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so (LoadError)

Libgcrypt is installed on system but libgcrypt.so.11 is not available on centos 8

**To Reproduce**

Install rails application with nokogiri on Centos 8.2

**Environment**

``` 
[root@...]# nokogiri -v
Traceback (most recent call last):
    5: from .../vendor/bundle/bin/nokogiri:29:in `<main>'
    4: from .../vendor/bundle/bin/nokogiri:29:in `load'
    3: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `<top (required)>'
    2: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `require'
    1: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:30:in `<top (required)>'
.../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:30:in `require': cannot load such file -- nokogiri/2.6/nokogiri (LoadError)
    6: from .../vendor/bundle/bin/nokogiri:29:in `<main>'
    5: from .../vendor/bundle/bin/nokogiri:29:in `load'
    4: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `<top (required)>'
    3: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `require'
    2: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:28:in `<top (required)>'
    1: from .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `rescue in <top (required)>'
.../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `require': libgcrypt.so.11: cannot open shared object file: No such file or directory - .../vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so (LoadError)

```

**Comment by flavorjones** [comment]
@fmonvoisin thanks for asking this question, and I'm sorry you're having trouble.

In the future, when submitting issues about installation, please choose the "Installation difficulties" issue template, and fill it out, because that's important information that we need in order to help you.

Here are the questions from that template, kindly respond? Thank you!

---

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

Please make sure to escape the file contents with triple-backticks.


**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

Please make sure to escape the file contents with triple-backticks.


**What operating system are you using?**

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

If MacOS, please note the version of XCode you have installed.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

If Windows, please note whether you're installing the precompiled gems, or compiling yourself with DevKit. Also please note the version of RubyInstaller you've installed.

---

I'd also ask: how did you install Ruby on this system? Was it a precompiled binary downloaded from somewhere else (for example, by RVM), or did you compile it locally?

**Comment by flavorjones** [comment]
Re-reading your original post ... it sounds like you may have "migrated" your application, along with its gems, from one version of CentOS to another. If that's the case, you'll need to re-install any gems that have compiled C extensions -- for example, nokogiri, bcrypt, sassc, etc.

**Comment by flavorjones** [comment]
Closing because OP hasn't responded. Please feel free to comment if you'd like to re-open the discussion!
