### ISSUE TITLE
Installation fails with space in XCode path

### ISSUE THREAD

**Issue by mycarrysun** [sparklemotion/nokogiri#2062]
**Describe the bug**

When XCode has a space in the file path (mine was `/Applications/Xcode 11.4.1.app`) the following command fails during installation:
```
/Applications/Xcode 11.4.1.app/Contents/Developer/usr/bin/make  all-recursive
make: /Applications/Xcode: No such file or directory
```

**To Reproduce**
This happens on `bundle install` when you have a space in the filename for Xcode on MacOS

**Expected behavior**

That nokogiri is installed successfully

**Environment**
MacOS Catalina 10.15.6
Ruby 2.6.5
Nokogiri 1.10.1

**Solution?**
I would imagine the solution to this is to surround the path in quotes when running the make command. If someone could point me in the direction of the install script I can put up a PR to fix.

**Comment by flavorjones** [comment]
@mycarrysun Thanks for asking this question, and sorry you're having trouble.

Without more information from you, I can't be absolutely sure, but I believe the issue you're having is due to a commonly-reported issue with libxml2. See also #1407, #1427, #1289, #1175, and #1891.

I've created #2055 to document this problem. In the meantime, you may want to try to compile and link against your system libraries, or else re-install xcode into a directory without spaces.

Sorry I can't be of more help here.
