### ISSUE TITLE
libxml2 and nokogiri decode html entities in node attributes

### ISSUE THREAD

**Issue by cpjolicoeur** [sparklemotion/nokogiri#214]
I have an xml document with the following content: http://gist.github.com/286925

Nokogiri ( and I'm guessing its libxml2 that actually is doing this and then passing it to nokogiri ) decodes the encoded HTML entities in the attribute values.

There is no way to get the raw string data from a nodes attribute values as the data is always decoded first.

**Comment by rosenfeld** [comment]
@tenderlove, regarding this: Out of curiosity, why do you need the "raw string"?

I also want the "raw string", so let me explain the reason. Currently, when parsing Edgar filing documents with Nokogiri I'm experiencing issues related to UTF-8 encoding of invalid chars. Edgar filings do not set the encoding but they only use ASCII chars and use `&#146;` for example to represent non ASCII chars. But this is translated to "\u0092" by the SAX parser and it causes trouble later when I write the final transformed document to some file, complaining that this char is not valid UTF8 or something like that. Leaving the raw `&#146;` would not cause any issues. I can confirm that by using a workaround to replace such pattern with `!!#146;` so that Nokogiri doesn't touch it and then I replace them back before saving to the file and the output is like I was expecting it to be.

Is it possible to tell libxml2 to not substitute such entity chars in the SAX parser and provide it as is (raw)?

**Comment by rosenfeld** [comment]
And here's a sample document so that you can have an idea: https://www.sec.gov/Archives/edgar/data/913077/000119312516429136/d100504dex21.htm
