### ISSUE TITLE
"incompatible library version" when upgrading Ruby

### ISSUE THREAD

**Issue by A7madXatab** [sparklemotion/nokogiri#2223]
So, i have upgraded my ruby version to `ruby 3.0.1`. I have a rails application with rspec.

When i try to run the command 
```
bundle exec rspec spec
```

i get the following error

```
oadError:
  incompatible library version - /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/nokogiri.bundle
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:25:in `require'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:25:in `rescue in <top (required)>'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:4:in `<top (required)>'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri.rb:11:in `require'
# /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri.rb:11:in `<top (required)>'
# ./spec/spec_helper.rb:3:in `require'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- nokogiri/3.0/nokogiri
#   /Users/ahmed/.rvm/gems/ruby-3.0.1/gems/nokogiri-1.11.3/lib/nokogiri/extension.rb:6:in `require'
```

I've tried fixing everything with rvm, but still this bug didint fix, any issues ?

Environment:
- ruby : 3.0.1
- nokogiri 1.11.3
- rails:  6.1
Thanks

**Comment by flavorjones** [comment]
Hi @A7madXatab, sorry you're having problems. I'll try to help.

The error you're seeing is similar to errors I've seen when Nokogiri has been copied across versions of Ruby (which it sounds like might be the case?). Because Nokogiri has a compiled C extension, a version compiled with Ruby 2.7 is not able to run with Ruby 3.0 -- the extension must be re-compiled.

Please uninstall Nokogiri and re-install it, following the instructions at https://nokogiri.org/tutorials/installing_nokogiri.html. If you're still having problems, please provide us with some more information (below).

I'd also like to suggest that you try to use the precompiled native gem if possible, which avoids this problem entirely by providing precompiled libraries for Ruby 2.5, 2.6, 2.7, and 3.0. You can read more about that at https://nokogiri.org/tutorials/installing_nokogiri.html as well.

---

**What is the complete output of `gem install` or `bundle install`?**



```
the output goes here
```


**If installation completed but is broken, what is the complete output from `nokogiri -v`?**



```
the output of "nokogiri -v" goes here
```



**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**



```
the mkmf.log file contents go here
```


**Tell us about your system!**

What is the output from `ruby -v`?

What is the output from `gem -v`?

What is the output from `gem env`?

```
the output of "gem env" output goes here
```


If you're using Bundler:
- what is the output from `bundle version`?
- what is the output from `bundle config`? (Take care to redact any credentials)

```
the output of "bundle config" goes here
```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
- the output of `gcc -v` or `clang -v`

**Comment by A7madXatab** [comment]
@flavorjones thank you very much, previously i have tried uninstalling and reinstalling the gem but no luck. Then 

> Please uninstall Nokogiri and re-install it, following the instructions at https://nokogiri.org/tutorials/installing_nokogiri.html. If you're still having problems, please provide us with some more information (below).

I have followed the installation process and installing the ruby platform for MacOS, specificlly this [part](https://nokogiri.org/tutorials/installing_nokogiri.html#installing-the-ruby-platform-gem).

All things said, thank you very much. Have a great day!.

**Comment by flavorjones** [comment]
OK, I'm glad you were able to figure it out.

I just want to recommend again that you try to use the precompiled native gem for MacOS, which should avoid the majority of installation and compatibility issues you might have. Good luck and happy coding!
