### ISSUE TITLE
[bug] v1.13.0 fails to load on ARM alpine linux

### ISSUE THREAD

**Issue by navied** [sparklemotion/nokogiri#2414]
Running nokogiri v1.13.0 on alpine arm images fails to load likely because it requires a musl compiled package

**Help us reproduce what you're seeing**

Reproduction steps for ARM based OS:

```
docker run --rm -it ruby:2.7.5-alpine sh
gem install nokogiri
irb
require 'nokogiri'

->> LoadError (cannot load such file -- nokogiri/nokogiri)

```
**Additional context**

It works perfectly fine on the docker ruby bullsye images

**Comment by xPalmer** [comment]
Hey all -- commenting in that I'm getting a 403 at RubyGems with `gem install nokogiri` starting yesterday, both locally and in builds. Possibly related.

```
$ gem install nokogiri
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.0-x64-unknown.gemspec.rz)
```

**Comment by navied** [comment]
> Hey all -- commenting in that I'm getting a 403 at RubyGems with `gem install nokogiri` starting yesterday, both locally and in builds. Possibly related.
> 
> Snippet from WSL1 Ubuntu
> 
> ```
> $ gem install nokogiri
> ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
>     bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.0-x64-unknown.gemspec.rz)
> ```

Looks like WSL linux is not reporting the OS properly here, think this probably a different issue

**Comment by flavorjones** [comment]
@navied Thanks for opening a new issue.

Unfortunately I don't know if I'm reproducing what you're seeing because you haven't provided enough information. The point of me asking you to open a new issue was to have you fill out the template so that I wouldn't have to ask a bunch of questions and do a back-and-forth.

So I'll tell you what I did, and you tell me what you're doing differently.

1. I fire up a Graviton instance
2. I install docker
3. I invoke a shell in an alpine docker container on that Graviton instance
4. `apk add gcompat`
5. `gem install nokogiri`
6. `nokogiri -v`

If I don't install `gcompat`, I get an error about loading `ld-linux-aarch64.so.1`. Is that the error you're seeing? If not, please answer the questions from https://raw.githubusercontent.com/sparklemotion/nokogiri/main/.github/ISSUE_TEMPLATE/1-installation-difficulties.md

**Comment by flavorjones** [comment]
I've added a new section to the installation page detailing the gcompat workaround:

https://nokogiri.org/tutorials/installing_nokogiri.html#linux-musl-error-loading-shared-library

Please let me know if that's helpful?

**Comment by navied** [comment]
@flavorjones the missing gcompat was it! Sorry should have done more googling into it clearly, I will close the issue now thanks for looking into it.

**Comment by Himanshu-holmes** [comment]
I am using slim getting this error after containerizing the app, bin/rails aborted!
app-1  | Bundler::GemRequireError: There was an error while trying to load the gem 'sprockets-rails'.
app-1  | Gem Load Error is: cannot load such file -- nokogiri                                                                                                
app-1  | Backtrace for gem load error is:                                                                                                                    
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/loofah-2.24.1/lib/loofah.rb:3:in `<main>'                                                                         
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rails-html-sanitizer-1.6.2/lib/rails-html-sanitizer.rb:5:in `<main>'                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/actionview-7.2.2.1/lib/action_view/helpers/sanitize_helper.rb:3:in `<main>'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/actionview-7.2.2.1/lib/action_view/helpers.rb:8:in `<main>'                                                       
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/sprockets-rails-3.5.2/lib/sprockets/rails/context.rb:1:in `<main>'                                                
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/sprockets-rails-3.5.2/lib/sprockets/railtie.rb:11:in `<main>'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/sprockets-rails-3.5.2/lib/sprockets/rails.rb:3:in `<main>'                                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:63:in `block (2 levels) in require'                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:58:in `each'                                                                 
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:58:in `block in require'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:52:in `each'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:52:in `require'                                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler.rb:215:in `require'                                                                     
app-1  | /rails/config/application.rb:7:in `<main>'                                                                                                          
app-1  | /rails/Rakefile:4:in `require_relative'                                                                                                             
app-1  | /rails/Rakefile:4:in `<main>'                                                                                                                       
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/rake_module.rb:29:in `load'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'                                                         
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/application.rb:740:in `raw_load_rakefile'                                                    
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/application.rb:126:in `block in load_rakefile'                                               
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/application.rb:214:in `standard_exception_handling'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/application.rb:125:in `load_rakefile'                                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'                               
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rake-13.3.0/lib/rake/rake_module.rb:59:in `with_application'                                                      
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:156:in `invoke_rake'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:73:in `block in invoke'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:149:in `with_argv'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:69:in `invoke'                                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands.rb:18:in `<main>'                                                             
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | bin/rails:4:in `<main>'
app-1  | Bundler Error Backtrace:
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:71:in `rescue in block (2 levels) in require'                                
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:62:in `block (2 levels) in require'                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:58:in `each'                                                                 
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:58:in `block in require'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:52:in `each'                                                                 
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:52:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler.rb:215:in `require'                                                                     
app-1  | /rails/config/application.rb:7:in `<main>'                                                                                                          
app-1  | /rails/Rakefile:4:in `require_relative'                                                                                                             
app-1  | /rails/Rakefile:4:in `<main>'                                                                                                                       
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:156:in `invoke_rake'                                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:73:in `block in invoke'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:149:in `with_argv'                                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:69:in `invoke'                                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands.rb:18:in `<main>'                                                             
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | bin/rails:4:in `<main>'                                                                                                                             
app-1  |                                                                                                                                                     
app-1  | Caused by:                                                                                                                                          
app-1  | LoadError: cannot load such file -- nokogiri                                                                                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/loofah-2.24.1/lib/loofah.rb:3:in `<main>'                                                                         
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/rails-html-sanitizer-1.6.2/lib/rails-html-sanitizer.rb:5:in `<main>'                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/actionview-7.2.2.1/lib/action_view/helpers/sanitize_helper.rb:3:in `<main>'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/actionview-7.2.2.1/lib/action_view/helpers.rb:8:in `<main>'                                                       
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/sprockets-rails-3.5.2/lib/sprockets/rails/context.rb:1:in `<main>'                                                
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/sprockets-rails-3.5.2/lib/sprockets/railtie.rb:11:in `<main>'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/sprockets-rails-3.5.2/lib/sprockets/rails.rb:3:in `<main>'                                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'                                                            
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:63:in `block (2 levels) in require'                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:58:in `each'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:58:in `block in require'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:52:in `each'                                                                 
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler/runtime.rb:52:in `require'                                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bundler-2.6.9/lib/bundler.rb:215:in `require'
app-1  | /rails/config/application.rb:7:in `<main>'                                                                                                          
app-1  | /rails/Rakefile:4:in `require_relative'                                                                                                             
app-1  | /rails/Rakefile:4:in `<main>'                                                                                                                       
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'                                          
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:156:in `invoke_rake'                                                        
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:73:in `block in invoke'                                                     
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:149:in `with_argv'
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/command.rb:69:in `invoke'                                                              
app-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.2.2.1/lib/rails/commands.rb:18:in `<main>'                                                             
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                           
app-1  | bin/rails:4:in `<main>'
app-1  | (See full trace by running task with --trace)
app-1 exited with code 1

**Comment by flavorjones** [comment]
@Himanshu-holmes You're having a completely different problem, I think. In any case, commenting on an issue that has been closed for over three years is unlikely to get you the help that you need.

Please review the [installation docs](https://nokogiri.org/tutorials/installing_nokogiri.html) and if you are still having problems, please open a new issue.
