### ISSUE TITLE
[bug] HTML5 fragment has extraneous head/body tags

### ISSUE THREAD

**Issue by dan42** [sparklemotion/nokogiri#2551]
```ruby
require "nokogiri" #1.13.6

puts Nokogiri.HTML("x").fragment("hello")
#=> hello

puts Nokogiri.HTML5("x").fragment("hello")
#=> <head></head><body>hello</body>
```
I'm fairly sure that a "fragment" is not supposed to include the `<head>` and `<body>` tags.

**Comment by stevecheckoway** [comment]
Hi @dan42,

Indeed it should not! I'll take a look.

**Comment by stevecheckoway** [comment]
So actually, I misread that initially as `Nokogiri::HTML5.fragment("hello")`.

The [HTML fragment parsing algorithm](https://html.spec.whatwg.org/multipage/parsing.html#parsing-html-fragments) takes an HTML element as input. When we call `Element#fragment()`, the element we're calling it on is the input to the algorithm.

In your example, you're calling it on a Document. I'm not sure what the expected output of that should be. One option would be to treat it as if we'd called it on the body element. This matches what you see using the HTML4 parser.
```ruby
> Nokogiri::HTML5("x").root.children[1].fragment("hello")
=> #(DocumentFragment:0x70b48 { name = "#document-fragment", children = [ #(Text "hello")] })
```

For both the HTML4 and HTML5 `Document#fragment`, we use the root `html` element as the context element.

After giving it some thought, the HTML5 output makes sense to me. If we parse just the string `hello` with the context element set to an `html` element, then on the first character, the parser will create an empty `head` element and a `body` element and then `hello` becomes a text node child of the `body` element.

And indeed, if we ask a browser to create a fragment with the `html` element as the context element, it produces the same output:

```javascript
> document.children[0].innerHTML = "hello"
"hello"
> document.children[0].innerHTML
"<head></head><body>hello</body>" 
```

I don't know why the HTML4 fragment parser doesn't do the same thing, but it's probably a limitation of libxml2.

So the question is what behavior do we want when `#fragment` is called on the document? My inclination is that the current behavior for HTML5 is confusing and should be changed to be as if we called it on a `body` element instead. This is a one line change.

```
diff --git a/lib/nokogiri/html5/document.rb b/lib/nokogiri/html5/document.rb
index d3b69431..e1bb446e 100644
--- a/lib/nokogiri/html5/document.rb
+++ b/lib/nokogiri/html5/document.rb
@@ -70,7 +70,7 @@ module Nokogiri
       end

       def fragment(tags = nil)
-        DocumentFragment.new(self, tags, root)
+        DocumentFragment.new(self, tags, nil)
       end

       def to_xml(options = {}, &block)
```

I suspect the HTML4 behavior for the fragment when called on the `html` element is simply wrong, but maybe we can just document it as being wrong rather than trying to fix it.

**Comment by dan42** [comment]
Thanks for the analysis.

For context, I'm using this to parse a string to nodes which will then be added to a document (doc1). Since the nodes already belong to doc1, they are easily moved from the DocumentFragment. If I use `Nokogiri::HTML5.fragment` this creates an extra Document object (doc2) to which the nodes belong, and then when I insert those nodes into doc1 they must be reparented, which is much slower.

The reason I'm not adding the string directly to doc1 is because I must do a bit of processing on the nodes before adding them to the document.

```ruby
tags = "hello"
doc = Nokogiri.HTML5("<div>")
div = doc.at('div')
frag = Nokogiri::HTML5.fragment(tags)                        #a
frag = doc.fragment(tags)                                    #b
frag = Nokogiri::HTML5::DocumentFragment.new(doc, tags, nil) #c
frag.xpath(...)
div << frag  #a is slow, b & c are fast, b is wrong
```

So from my perspective the one-line change you suggested is perfect.

I understand why "the HTML5 output makes sense" in a technical sense, but I find it
1. not so useful; the output fits the notion of "document" more than "fragment". What's the use case?
2. not what I expected from `doc.fragment(tags)`; I expected it to be equivalent to `Nokogiri::HTML5.fragment(tags)` but with an existing Document object instead of allocating a new one

I think part of the issue is that `Nokogiri::HTML.fragment` works that way, so when I upgraded Nokogiri to 1.12.0 I just changed the code to `Nokogiri::HTML5.fragment` and expected it to work the same way.

**Comment by stevecheckoway** [comment]
I think the correct way to use this API is to call `#fragment` on the actual element you want to be the ultimate parent, in this case, the `div`.

```ruby
tags = 'hello'
doc = Nokogiri.HTML5('<div>')
div = doc.at('div')
frag = div.fragment(tags)
div << frag
```

To be clear, I'm not sure what the behavior calling `#fragment` on a document is supposed to have. It's not something the standard addresses and it's not something that could come up in the browser context (to the best of my limited knowledge). So I think this is a choice Nokogiri has to make. The current choice is for the `Document` to forward the `#fragment` to the root element. The problem is the HTML4 and HTML5 parsers have different behaviors when using `html` elements as the fragment context.

@flavorjones, do you have thoughts on this?

**Comment by dan42** [comment]
> I think the correct way to use this API is to call `#fragment` on the actual element you want to be the ultimate parent, in this case, the `div`.

Ah, that's really insightful.

But in that order of ideas, if I wanted the context to be the root element, then I would do `doc.root.frament(tags)` (similar to that `document.children[0].innerHTML` example earlier) and in that case I would find it totally normal to have those head/body tags.

**Comment by stevecheckoway** [comment]
I agree. I'll try to find some time to add tests to #2553. Unfortunately, this is a very busy time of the semester for me (dealing with grading and students graduating) so it may be a bit before I get to it. If someone else wants to finish that PR by adding tests, that's fine with me.

It would be good to know what the Java implementation does, but I've never used Jython.
