### ISSUE TITLE
[bug] jruby NPE when serializing an unparented HTML node

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2559]
**Please describe the bug**

```ruby
Nokogiri::HTML::Document.parse("<div></div>").create_text_node("asdf").to_s
```

results in

```
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
      isHtmlScript at nokogiri/internals/SaveContextVisitor.java:812
             enter at nokogiri/internals/SaveContextVisitor.java:833
            accept at nokogiri/XmlText.java:75
   native_write_to at nokogiri/XmlNode.java:1352
              call at nokogiri/XmlNode$INVOKER$i$1$0$native_write_to.gen:-1
              call at org/jruby/internal/runtime/methods/JavaMethod.java:846
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:329
              call at org/jruby/runtime/callsite/CachingCallSite.java:87
```

**Expected behavior**

Unparented nodes should serialize normally, as they do in the CRuby implementation

**Comment by cbasguti** [comment]
I've investigated the reported bug in the Nokogiri project, and I believe I've identified the cause. It seems that the issue lies within the [isHtmlScript](https://imgur.com/a/Mj58Rts) and [isHtmlStyle](https://imgur.com/a/Mj58Rts) functions, where a [NullPointerException](https://imgur.com/a/Mj58Rts) occurs due to the inability to evaluate a null object in Java.

To address this, I suggest making the following modifications:

- Add a null check for the getParentNode() method's return value before performing any comparisons.
- If the parent node is null or does not match the expected tag name, log an appropriate message and return false.

As this is my first contribution to the project, I'm excited to learn from your feedback. I will open a draft PR to propose these changes and verify their effectiveness.

Thank you for your guidance and support!
Best regards.
