### ISSUE TITLE
[install] gem installation fails due to access right issues on rubygems.org

### ISSUE THREAD

**Issue by wolfgang371** [sparklemotion/nokogiri#2580]
I already reported this at rubygems.org and got this answer:

> This support email is for issues related to RubyGems.org the website and RubyGems the client. Please use Stackoverflow or Github issues for help with specific gems.

Thanks!

-----

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
sudo gem install nokogiri
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.6-x64-unknown.gemspec.rz)
```

**Tell us about your system!**

What is the output from `ruby -v`?
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

What is the output from `gem -v`?
```
2.7.6
```

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /home/wolfgang/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.5
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/wolfgang/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.5.0
     - /home/wolfgang/.gem/ruby/2.5.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/wolfgang/bin
     - /home/wolfgang/.local/bin
     - /home/wolfgang/bin
     - /home/wolfgang/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

If Linux or a BSD variant, please note:
- the distro you're using: `Ubuntu 18.04`
- the output of `uname -a` `Linux secret 5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- the contents of `/etc/lsb-release`.
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
```

**Comment by flavorjones** [comment]
Thanks for opening this issue! I'm sorry you're getting passed around, but I can help.

The issue you're seeing is actually due to the behavior of older versions of `gem` which aren't smart enough to look at the [`required_ruby_version`](https://guides.rubygems.org/specification-reference/#required_ruby_version) value in each gem version's gemspec.

The latest Nokogiri is v1.13.6 which doesn't support Ruby 2.5 (you can see this in the [`nokogiri.gemspec`](https://github.com/sparklemotion/nokogiri/blob/v1.13.6/nokogiri.gemspec#L43)). However, the version of `gem` that you're running, v2.7.6, tries to grab the latest version without first checking that it is compatible with the version of Ruby you're running.

You can get around this in two ways:

1. manually pick a version of Nokogiri that supports your version of Ruby (the v1.12.x series is the last branch that supported Ruby 2.5, so you can try `gem install nokogiri -v "~> v1.12.0"`)
2. upgrade to a newer version of rubygems by running `gem update --system`

I recommend the second option, upgrade rubygems. Here's what it looked like for me:

```
$ ruby -v
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]

$ gem -v
2.7.6.3

$ gem install nokogiri
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.6-x64-unknown.gemspec.rz)

$ gem update --system
Updating rubygems-update
rbenv: cannot rehash: /home/flavorjones/.rbenv/shims/.rbenv-shim exists
Successfully installed rubygems-update-3.3.16
... snip ...
RubyGems installed the following executables:
	/home/flavorjones/.rbenv/versions/2.5.9/bin/gem
	/home/flavorjones/.rbenv/versions/2.5.9/bin/bundle
	/home/flavorjones/.rbenv/versions/2.5.9/bin/bundler

RubyGems system software updated

$ gem -v
3.3.16

$ gem install nokogiri
Successfully installed nokogiri-1.12.5-x86_64-linux
Parsing documentation for nokogiri-1.12.5-x86_64-linux
Done installing documentation for nokogiri after 1 seconds
1 gem installed
```

I hope this helps!
