### ISSUE TITLE
Not able to get the node having attribute as numeric name

### ISSUE THREAD

**Issue by dsinghsf** [sparklemotion/nokogiri#2793]
**Please describe the bug**
I am parsing a file Xml file as below

```
<tag1 131.180.212.121>
  <tag2 *>
      bounce-after 4h
  </tag2>
</tag1>
```

My requirment is, i have  these lot of files containing above tags and i get very frequent request to add the tag and the following text for a matching tag1 and ip combo. I am trying to write a script to do that. But while searching the nodes using xpath, i am not able to get the node as it has the ip as attribute. Have tried lot of things but couldnt able to find any work around. Please let me know if i am missing somthing

**Help us reproduce what you're seeing**

Here is my code
> file = 'abc.xml'
> f = File.open(file)
> node = Nokogiri::XML(f)
> f.close
> puts node.xpath('tag1 131.180.212.121')

**Expected behavior**

It should return the children nodes.

**Comment by flavorjones** [comment]
Hi, @dsinghsf, thanks for asking this question.

Unfortunately, the markup you've provided is not valid! Let's take a look at how it gets parsed by libxml2:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

xml = <<~XML
  <tag1 131.180.212.121>
    <tag2 *>
        bounce-after 4h
    </tag2>
  </tag1>
XML

doc = Nokogiri::XML(xml)
doc.to_xml # => "<?xml version=\"1.0\"?>\n<tag1/>\n"
```

If we look at the errors on the document, we can see what's happening:

```
doc.errors
# => [#<Nokogiri::XML::SyntaxError: 1:7: FATAL: error parsing attribute name>,
#     #<Nokogiri::XML::SyntaxError: 1:7: FATAL: attributes construct error>,
#     #<Nokogiri::XML::SyntaxError: 1:7: FATAL: Couldn't find end of Start Tag tag1 line 1>,
#     #<Nokogiri::XML::SyntaxError: 1:7: FATAL: Extra content at the end of the document>]
```

The problem here is that the "attribute" which is `131.180.212.121` or some other numeric IP address doesn't start with a valid [`NameStartChar`](https://www.w3.org/TR/xml/#NT-NameStartChar).

Unfortunately, because this is not valid XML, you're going to have a hard time using any standard XML tools to parse and manipulate it.

An alternative might be to make this a proper attribute, something like `ip=131.180.212.121`:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

xml = <<~XML
  <tag1 ip="131.180.212.121">
    <tag2 ip="*">
        bounce-after 4h
    </tag2>
  </tag1>
XML

doc = Nokogiri::XML(xml)
doc.to_xml
# => "<?xml version=\"1.0\"?>\n" +
#    "<tag1 ip=\"131.180.212.121\">\n" +
#    "  <tag2 ip=\"*\">\n" +
#    "      bounce-after 4h\n" +
#    "  </tag2>\n" +
#    "</tag1>\n"

doc.errors
# => []
```

in which case you can use an xpath query like this:

```ruby
doc.xpath("//tag1[@ip='131.180.212.121']")
# => [#<Nokogiri::XML::Element:0xb4 name="tag1" attributes=[#<Nokogiri::XML::Attr:0x3c name="ip" value="131.180.212.121">] children=[#<Nokogiri::XML::Text:0x50 "\n  ">, #<Nokogiri::XML::Element:0x8c name="tag2" attributes=[#<Nokogiri::XML::Attr:0x64 name="ip" value="*">] children=[#<Nokogiri::XML::Text:0x78 "\n      bounce-after 4h\n  ">]>, #<Nokogiri::XML::Text:0xa0 "\n">]>]
```

Hope this helps?

**Comment by dsinghsf** [comment]
Hi @flavorjones 
Yeah, seems like that the issue. The thing is this is legacy design in our system to store the data in this format, will plan some major revamp for below
> proper attribute, something like ip=131.180.212.121

Anyways, Thanks for help.. seems like i have to by old regex way for short term and plan for the permanent fix.
