### ISSUE TITLE
[bug] Relax the version warning about mismatch between compile time versions and runtime versions

### ISSUE THREAD

**Issue by darix** [sparklemotion/nokogiri#2978]
Back in a913af57936869bf54acedac1586c9884dbfabec nokogiri got a warning if it dynamically loaded a different version than it was compiled against. I can see value for it if nokogiri is loading an older version of the library at runtime. But could we allow loading newer versions dynamically? This would allow linux distributions to ship a libxml2 update without also having to rebuild nokogiri.

```
diff --git a/lib/nokogiri/version/info.rb b/lib/nokogiri/version/info.rb
index a5f45283..31454ab9 100644
--- a/lib/nokogiri/version/info.rb
+++ b/lib/nokogiri/version/info.rb
@@ -73,11 +73,11 @@ module Nokogiri
       warnings = []
 
       if libxml2?
-        if compiled_libxml_version != loaded_libxml_version
+        if compiled_libxml_version > loaded_libxml_version
           warnings << "Nokogiri was built against libxml version #{compiled_libxml_version}, but has dynamically loaded #{loaded_libxml_version}"
         end
 
-        if compiled_libxslt_version != loaded_libxslt_version
+        if compiled_libxslt_version > loaded_libxslt_version
           warnings << "Nokogiri was built against libxslt version #{compiled_libxslt_version}, but has dynamically loaded #{loaded_libxslt_version}"
         end
       end
```

**Comment by flavorjones** [comment]
@darix Thanks for asking about this.

The warning still provides value to the rubygem distribution (which is the primary distribution mechanism in the Ruby community), because it lets users know they may not get the behavior they expect (or that Nokogiri expects). More specifically, it lets users know that they may have compiled against a different version than is being found at runtime (compiler flags versus runtime ld library path issues). This is an important safety check for people who are building their own C extension.

If you're redistributing Nokogiri, and these safety checks don't make sense for your users or distribution mechanism, you may want to consider a downstream patch to remove this warning. But I don't think it's a good idea to remove the warning from the upstream project.

**Comment by darix** [comment]
as I said ... i can see the value if an older version is loaded at runtime ... but as long as the so version is correct loading a newer version shouldnt warrant a warning.

**Comment by flavorjones** [comment]
@darix In the context of a linux distro, where you rely on ABIs and users expect up-to-date packages, I completely understand that this is how you feel. Please feel free to patch out the warnings!
