### ISSUE TITLE
nokogiri-1.5.0-java inner_text is not respecting inner nodes

### ISSUE THREAD

**Issue by postmodern** [sparklemotion/nokogiri#521]
I noticed that `Nokogiri::HTML::Node#inner_text` was traversing the entire document on JRuby 1.6.3.
## Steps to Reproduce

```
require 'rubygems'
require 'nokogiri'

doc = Nokogiri::HTML(%{
      <html>
        <body>Hello</body>
      </html>
})

doc.at('body').inner_text
```
## Expected Result (Ruby 1.9.2-p290)

```
"Hello"
```
## Actual Result (JRuby 1.6.3)

```
"Hello\n      \n"
```

**Comment by flavorjones** [comment]
The behavior has improved a bit since this bug was filed, with only a single "\n" being emitted by JRuby. This has to do with how JRuby / Xerces formats the document:

```ruby
doc = Nokogiri::HTML(%{
      <html>
        <body>Hello</body>
      </html>
})

doc.to_html.inspect
# => "<html><head></head><body>Hello\n</body></html>"
```

You can see that Xerces adds a newline at the end of the body text. This behavior is inherited by Nokogiri, and unfortunately there isn't anything we can easily do about that difference.
