### ISSUE TITLE
inner_text joins text without whitespace

### ISSUE THREAD

**Issue by DougPuchalski** [sparklemotion/nokogiri#636]
Joining `<span>one</span><span>two</span>` inner_text elements without whitespace results in `onetwo` rather than `one two`. Votes for a single space when joining?

https://github.com/tenderlove/nokogiri/commit/be67bd3eb17bda8b08a14a512980983691376c65#lib/nokogiri/xml/node_set.rb-P7

**Comment by feliperaul** [comment]
@tenderlove Please reconsider reopening this one. It's a bug. When I ask for the text of an element, you can't change it. If I have `<span>Experts</span><span>exchange</span>', `.text` output is `expertsexchange`... it's actually changing the text!

Regarding the ambiguity, you just add one whitespace and that's all. If there's already other whitespaces there, it's up to the user use `.strip` or something like that. But please don't concatenate strings that belongs to different HTML elements. 

Had a nasty bug because of this.

**Comment by feliperaul** [comment]
In the meantime, a workaround is using this:
`Nokogiri::HTML(str).xpath('//text()').map(&:text).join(' ')`
source: http://stackoverflow.com/questions/28449761/replace-html-tags-with-whitespaces

**Comment by knu** [comment]
Whitespace is a language-specific choice for a word separator.  There are languages in the world such as Japanese that do not use space for separating words or sentences.

As you may know, the XML/HTML and DOM specifications are clear about how to deal with whitespaces, so unless this argument is based on some standards and backward compatibility is fully taken into account, we could never be able to buy it.

I, for one, have never seen a DOM API that complements implicit whitespaces between nodes, and I think an XPath equivalent for `inner_text()` is `string(.)`, which simply concatenates texts without any seperator:

```ruby
Nokogiri::HTML(str).xpath('string(.)')  #=> "onetwo"
```

**Comment by ar7max** [comment]
Firefox
JavaScript
```
D = div element of  '<span>one</span><span>two</span>'
D.innerText returns 'onetwo'
D.textContent returns 'some whitespaces onetwo some whitespaces'
```
So, whats a problem? What did you expect from ```inner_text```?
