### ISSUE TITLE
xpath() around 10x slower in JRuby

### ISSUE THREAD

**Issue by ghostganz** [sparklemotion/nokogiri#741]
For some reason the xpath() method is a _lot_ slower in nokogiri-java 1.5.5 than the MRI version.

I have code that processes around 1.5 MB of XML, using a lot of nested xpath loops. It takes only 1.7 seconds in MRI but around 150 seconds in JRuby 1.6.7.2 on Java 7. Running with VisualVM shows that almost all time is spent in XmlXpathContext.tryGetNodeSet().

I think this is a regression, because I don't recall this being so slow with older versions of Nokogiri.

**Comment by flavorjones** [comment]
@jvshahid this test is failing in the [concourse pipelines](https://ci.nokogiri.org/teams/main/pipelines/nokogiri/jobs/jruby-9.1/builds/1), because of noisy neighbor problems when all the tests are running at the same time.

Is there a real worry about regression here? If not, maybe we just delete it rather than make it more complicated? I'm sensitive to the amount of work we'd need to put in to make this not-brittle.

**Comment by jvshahid** [comment]
I'm not happy with that test either, but I don't know if there's a better way to test performance regression. I'm okay with deleting it. That code doesn't change frequently to justify having the brittle tests.

**Comment by flavorjones** [comment]
Roger, gonna skip it for all platforms.

**Comment by flavorjones** [comment]
See 2d2893a
