### ISSUE TITLE
JRuby/CRuby incompatibility for namespaces

### ISSUE THREAD

**Issue by doxavore** [sparklemotion/nokogiri#779]
Running this code against Nokogiri 1.5.5 (C and Java):

``` ruby
require 'nokogiri'
doc = Nokogiri::XML::Builder.new do |xml_base|
  xml_base.send('multistatus', 'xmlns:D' => 'DAV:') do
    xml_base.parent.namespace = xml_base.parent.namespace_definitions.first
    xml = xml_base['D']

    xml.response do
      xml.href "some url one"
    end
    xml.response do
      xml.href "some url two"
    end
  end
end

puts doc.to_xml
```

Results in this output for CRuby, as I would expect:

```
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:">
  <D:response>
    <D:href>some url one</D:href>
  </D:response>
  <D:response>
    <D:href>some url two</D:href>
  </D:response>
</D:multistatus>
```

However, in JRuby, the output is:

```
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:">
  <D:response>
    <href>some url one</href>
  </D:response>
  <response>
    <href>some url two</href>
  </response>
</D:multistatus>
```

It loses track of the namespace after a while. I'm not sure if this is the best way to do this or not, but I'm sure it shouldn't be giving different things.

**Comment by avinmathew** [comment]
I've just encountered the same issue on Nokogiri 1.6.6.2.

The namespace allocated to a child element is dependent on if a default namespace exists.

**Without default namespace**

```ruby
Nokogiri::XML::Builder.new do |xml|
  xml.root('xmlns:p' => 'ns') do
    xml.parent.namespace = xml.parent.namespace_definitions.first
	xml.child
  end
end.doc.root.to_xml
```

Using MRI:
```xml
<p:root xmlns:p="ns">
  <p:child/>
</p:root>
```

Using JRuby:
```xml
<p:root xmlns:p="ns">
  <child/>
</p:root>
```

The child element is assigned a different namespace.

**With default namespace**

```ruby
Nokogiri::XML::Builder.new do |xml|
  xml.root('xmlns:p' => 'ns', 'xmlns' => 'ns2') do
    xml.parent.namespace = xml.parent.namespace_definitions.first
	xml.child
  end
end.doc.root.to_xml
```

Using MRI:
```xml
<p:root xmlns:p="ns" xmlns="ns2">
  <child/>
</p:root>
```

Using JRuby:
```xml
<p:root xmlns="ns2" xmlns:p="ns">
  <child/>
</p:root>
```

The child element is assigned the same namespace.

So MRI makes the assumption that if no namespace prefix is specified and there isn't a default namespace specified, then adopt the prefix of the root. JRuby doesn't make that assumption.

Having a read of http://www.w3.org/TR/xml-names/#defaulting, I would lean toward JRuby's behaviour as safer, since my understanding from the spec is that it's possible to have an element with no namespace name.

**Comment by flavorjones** [comment]
Apologies for not responding for such an embarrassingly long time.

This behavior was changed earlier this year and is now configurable, for details please see:
- https://github.com/sparklemotion/nokogiri/pull/2320
- https://nokogiri.org/rdoc/Nokogiri/XML/Document.html#namespace_inheritance-instance_method
- https://nokogiri.org/rdoc/Nokogiri/XML/Builder.html#label-Namespace+inheritance
