### ISSUE TITLE
Empty string does not fail schema validation with JRuby like it does with MRI

### ISSUE THREAD

**Issue by mrkcor** [sparklemotion/nokogiri#783]
With Nokogiri 1.5.5 on JRuby validating an empty document does not result in an error, while with MRI it does. 

If you try the below snippet in MRI and JRuby (XML schema taken from #642, perhaps there is some relation between the issues -- atleast for JRuby):

``` ruby
require 'nokogiri'

xsd_data = <<-XSD
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.example.org/contactExample"
  xmlns:tns="http://www.example.org/contactExample"
  elementFormDefault="qualified">
  <xs:element name="Contacts"></xs:element>
</xs:schema>
XSD

xsd = Nokogiri::XML::Schema.new(xsd_data)

empty_xml = Nokogiri::XML("")

xsd.validate(empty_xml)
#=> MRI: [#<Nokogiri::XML::SyntaxError: The document has no document element.>]
#=> JRuby: []

xsd.valid?(empty_xml)
#=> MRI: false
#=> JRuby: true
```

**Comment by flavorjones** [comment]
I've create #2641 which includes a pending (on JRuby) test that captures the issue.

I looked into this and I wasn't able to find the root cause -- but I traced enough to verify that [`javax.xml.validation.Validator`](https://docs.oracle.com/javase/8/docs/api/javax/xml/validation/Validator.html#validate-javax.xml.transform.Source-) isn't calling the [`SchemaErrorHandler`](https://github.com/sparklemotion/nokogiri/blob/main/ext/java/nokogiri/internals/SchemaErrorHandler.java) at all in this case. It's not clear to me if that's a bug in the implementation or not, but I do know that I need help from someone who can dig deeper into the Java internals.

**Comment by flavorjones** [comment]
PR #3260 will fix this.
