### ISSUE TITLE
JRuby Nokogiri indents XML if :indent is specified even if :save_with => 0 specified 

### ISSUE THREAD

**Issue by bhollis** [sparklemotion/nokogiri#833]
I'm using Nokogiri 1.5.6 with JRuby 1.7.2 (1.9 mode):

```
ruby --version
jruby 1.7.2 (1.9.3p327) 2013-01-04 302c706 on Java HotSpot(TM) 64-Bit Server VM 1.6.0_37-b06-434-11M3909 [darwin-x86_64]
```

Test script:

``` ruby
require 'nokogiri'

x = Nokogiri::XML("<foo><bar>baz</bar></foo>")

puts "INDENT:"
puts x.to_xml(:indent => 2, :save_with => 0)

puts "NO INDENT:"
puts x.to_xml(:save_with => 0)
```

In JRuby:

```
INDENT:
<?xml version="1.0"?>
<foo>
  <bar>baz</bar>
</foo>
NO INDENT:
<?xml version="1.0"?>
<foo><bar>baz</bar></foo>
```

In MRI 1.9.3:
INDENT:

```
<?xml version="1.0"?>
<foo><bar>baz</bar></foo>
NO INDENT:
<?xml version="1.0"?>
<foo><bar>baz</bar></foo>
```

It seems like in the JRuby version, specifying `:indent` forces indentation even if `:save_with => 0` is specified (which should turn off indenting since it's missing the `FORMAT` flag).

**Comment by flavorjones** [comment]
Ugh, this is so complicated and has so much history in it ...

https://github.com/sparklemotion/nokogiri/issues/415 led us to the decision to turn OFF JRuby formatting by default (but it's ON by default in CRuby).

As a compensating factor, we then made JRuby turn formatting back on if indentation is provided (assuming reasonably that people probably want formatting if they're providing indentation).

However, if you explicitly say "no formatting" and also provide indentation, then yes the behavior will be different between the implementations, because CRuby (libxml2) will only use indentation if formatting is on.

The right thing to do here _might_ be to have CRuby _also_ implicitly turn formatting on if indentation is provided, but this would likely surprise people who have explicitly asked for formatting to be turned off.

While I acknowledge this is not working as expected, the obvious workaround is to not provide indentation options if you don't want it formatted, and so I'm going to mark this "wontfix".

Thanks for your patience, and sorry I didn't respond on this sooner.
