### ISSUE TITLE
Different behavior for HTML.fragment under JRuby / pure-java

### ISSUE THREAD

**Issue by matpowel** [sparklemotion/nokogiri#863]
Hi all,

With the pure-java version of Nokogiri, we're seeing it add surrounding tags to HTML fragments. For example in IRB:

In REE (Nokogiri 1.5.5)

``` ruby
require "rubygems" # => true
require "nokogiri"    # => true
# => "<tr><td>yeah yeah</td></tr>" 
```

In JRuby (Nokogiri-java 1.5.5)

``` ruby
require "rubygems" # => true
require "nokogiri"    # => true
Nokogiri::HTML.fragment( "<tr><td>yeah yeah</td></tr>" ).to_html
# => "<table><tr><td>yeah yeah</td></tr></table>"
```

This causes a bunch of problems in our rails app because we do some manipulation on a rails partial as a fragment which has a bunch of table rows supposed to be squirted into an already existing table (so we obviously don't want it wrapped again!)

Thanks.

**Comment by flavorjones** [comment]
@matpowel Apologies for not responding sooner.

The behavior being described here is inherited by Nokogiri from the underlying parsing engine, in this case nekohtml. As a result there's not much Nokogiri can easily do to make the behaviors between parsers identical in every case.

A workaround for the described problem might be to select the `tr` element after parsing, like this:

```
Nokogiri::HTML.fragment( "<tr><td>yeah yeah</td></tr>" ).at_css("tr")
```

However I'll note that the parser's behavior has changed in the intervening years and now when I run this snippet I only get the text contents ("yeah yeah") which I imagine is due to nekohtml throwing away the `tr` tag because it's not present in a `table` tag. A workaround now might be to wrap your fragment in a `table` tag and still pull out the `tr` tag using `at_css`.

Sorry I can't be of more help here. :neutral_face:
