### ISSUE TITLE
XPath doesn't support square brackets to specify capture

### ISSUE THREAD

**Issue by truekonrads** [sparklemotion/nokogiri#916]
In Nokogiri, you can't use xpath expression like //form[/input[@name='foobar']] to get a "form" element which has a  child "input" with attribute "name" with value "foobar".

**Comment by flavorjones** [comment]
Hi, apologies for not responding for such an embarrassingly long time.

Brackets (and even nested brackets) are fully supported by Nokogiri (or maybe more accurately by libxml2's xpath 1.0 implementation). I think your XPath syntax is incorrect.

Here's an example of how to do what I *think* you're trying to do:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

html = <<~HTML
  <html>
    <body>
      <form>
        <input name="asdf">asdf</input>
        <input name="foobar">asdf</input>
      </form>
    </body>
  </html>
HTML

doc = Nokogiri::HTML4::Document.parse(html)

puts doc.xpath("//form[input[@name='foobar']]")
# => <form>
#      <input name="asdf">asdf
#      <input name="foobar">asdf
#    </form>
```

Please note that you originally reported using this XPath query:

```
//form[/input[@name='foobar']]
```

but the `/` before `input` will never match because it pins the subsearch to the root node. Instead the working query in my example is:

```
//form[input[@name='foobar']]
```

which does what you want. You could also use either of these two forms:

```
//form[./input[@name='foobar']]
//form[//input[@name='foobar']]
```

Hope this helps, and apologies again for not responding promptly.

**Comment by flavorjones** [comment]
(Updated previous comment to remove an incorrect query that used `//` for the subsearch.)
