### ISSUE TITLE
 un-expected result with the method `#to_html`.

### ISSUE THREAD

**Issue by aruprakshit** [sparklemotion/nokogiri#969]
Hi,

I am getting un-expected result with the method `#to_html`.

```
require 'nokogiri'
require 'open-uri'

doc = Nokogiri.HTML(open('http://www.s-techent.com/ATA100.htm'))
puts doc.at_xpath("(//table)[2]/tr/td//a[@name='[09]']").to_html(:encoding => 'utf-8')
# => <a name="%5B09%5D"></a>
```

expected output is : `<a NAME="[09]"></a>`

**Comment by flavorjones** [comment]
Apologies for not responding on this for so many years.

@knu is correct in his diagnosis. The behavior you're describing is inherited from the underlying HTML4 library, libxml2. Here's the C code that controls URI-escaping of certain HTML attributes at serialization-time (when the document is printed):

https://gitlab.gnome.org/GNOME/libxml2/blob/v2.9.2/HTMLtree.c#L714-718

Specifically, `href`, `action`, `src`, and `name` (but only within an anchor) are always escaped when generating HTML -- basically, anything that could be a URI reference.

Fortunately, since 2013 things have improved somewhat, and you can now use Nokogiri's HTML5 parser (which uses libgumbo) to handle this better:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

html = <<~EOF
  <html>
    <body>
      <a name='[09]'>hello</a>
EOF

html4_doc = Nokogiri::HTML4::Document.parse(html)
puts html4_doc.to_html
# => <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
# <html>
#   <body>
#     <a name="%5B09%5D">hello</a>
# </body>


html5_doc = Nokogiri::HTML5::Document.parse(html)
puts html5_doc.to_html
# => <html><head></head><body>
#     <a name="[09]">hello</a>
# </body></html>
```

Hopefully you're able to use the HTML5 parser (available in Nokogiri v1.12+, or before then you can install Nokogumbo separately). Apologies again for my slow response.
